// Code generated by tools/npcimport; DO NOT EDIT.
//
// Source: helbreath-v3.82-master/Server/Core/NPC.cfg
// This file adds NPC types not already defined in npc.go.
package npc

import "time"

func init() {
	NpcTypes[1] = &NpcType{
		ID: 1, Name: "XB-Aresden", SpriteType: 1,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[2] = &NpcType{
		ID: 2, Name: "XW-Aresden", SpriteType: 2,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[3] = &NpcType{
		ID: 3, Name: "XY-Aresden", SpriteType: 3,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[4] = &NpcType{
		ID: 4, Name: "YB-Aresden", SpriteType: 4,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[5] = &NpcType{
		ID: 5, Name: "YW-Aresden", SpriteType: 5,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[6] = &NpcType{
		ID: 6, Name: "YY-Aresden", SpriteType: 6,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[35] = &NpcType{
		ID: 35, Name: "Energy-Sphere", SpriteType: 35,
		HP: 100, MinDamage: 1, MaxDamage: 0,
		Defense: 10, DEX: 10, XP: 3749,
		AggroRange: 7, MoveSpeed: 60000, AttackSpeed: 60000, WanderRange: 8,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeSmall, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 1 * time.Second,
		MagicHitRatio: 200,
	}

	NpcTypes[36] = &NpcType{
		ID: 36, Name: "AGT-Aresden", SpriteType: 36,
		HP: 5000, MinDamage: 5, MaxDamage: 40,
		Defense: 50, DEX: 500, XP: 4000,
		AggroRange: 8, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 0,
		DiceThrow: 5, DiceRange: 8,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[37] = &NpcType{
		ID: 37, Name: "CGT-Aresden", SpriteType: 37,
		HP: 5000, MinDamage: 10, MaxDamage: 140,
		Defense: 50, DEX: 500, XP: 4000,
		AggroRange: 8, MoveSpeed: 1800, AttackSpeed: 1800, WanderRange: 0,
		DiceThrow: 10, DiceRange: 14,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[38] = &NpcType{
		ID: 38, Name: "MS-Aresden", SpriteType: 38,
		HP: 5000, MinDamage: 1, MaxDamage: 0,
		Defense: 50, DEX: 500, XP: 1000,
		AggroRange: 8, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[39] = &NpcType{
		ID: 39, Name: "DT-Aresden", SpriteType: 39,
		HP: 5000, MinDamage: 1, MaxDamage: 0,
		Defense: 50, DEX: 500, XP: 1000,
		AggroRange: 8, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[40] = &NpcType{
		ID: 40, Name: "ESG-Aresden", SpriteType: 40,
		HP: 8000, MinDamage: 1, MaxDamage: 0,
		Defense: 50, DEX: 500, XP: 1000,
		AggroRange: 8, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[41] = &NpcType{
		ID: 41, Name: "GMG-Aresden", SpriteType: 41,
		HP: 500000, MinDamage: 1, MaxDamage: 0,
		Defense: 5000, DEX: 500, XP: 55450,
		AggroRange: 8, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
		BossType: 1,
		Mana: 80, MaxMana: 80,
	}

	NpcTypes[42] = &NpcType{
		ID: 42, Name: "ManaStone", SpriteType: 42,
		HP: 500000, MinDamage: 1, MaxDamage: 0,
		Defense: 5000, DEX: 500, XP: 1,
		AggroRange: 8, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideNeutral,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
		BossType: 1,
	}

	NpcTypes[43] = &NpcType{
		ID: 43, Name: "LWB-Aresden", SpriteType: 43,
		HP: 2500, MinDamage: 10, MaxDamage: 50,
		Defense: 450, DEX: 500, XP: 6000,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 10, DiceRange: 5,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 8,
		RespawnDelay: 60 * time.Second,
		CanFlee: true, FleeHPPct: 10,
		INT: 70,
	}

	NpcTypes[44] = &NpcType{
		ID: 44, Name: "GHK", SpriteType: 44,
		HP: 3500, MinDamage: 10, MaxDamage: 90,
		Defense: 450, DEX: 500, XP: 8000,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 10, DiceRange: 9,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 4,
		RespawnDelay: 60 * time.Second,
		CanFlee: true, FleeHPPct: 10,
		INT: 70,
	}

	NpcTypes[45] = &NpcType{
		ID: 45, Name: "GHKABS", SpriteType: 45,
		HP: 8000, MinDamage: 13, MaxDamage: 156,
		Defense: 450, DEX: 1000, XP: 20000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 13, DiceRange: 12,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 5,
		RespawnDelay: 60 * time.Second,
		INT: 70,
	}

	NpcTypes[46] = &NpcType{
		ID: 46, Name: "TK", SpriteType: 46,
		HP: 3500, MinDamage: 10, MaxDamage: 90,
		Defense: 450, DEX: 500, XP: 8000,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 10, DiceRange: 9,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 4,
		RespawnDelay: 60 * time.Second,
		CanFlee: true, FleeHPPct: 10,
		INT: 70,
	}

	NpcTypes[47] = &NpcType{
		ID: 47, Name: "BG", SpriteType: 47,
		HP: 8000, MinDamage: 13, MaxDamage: 156,
		Defense: 450, DEX: 1000, XP: 20000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 13, DiceRange: 12,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 5,
		RespawnDelay: 60 * time.Second,
		INT: 70,
	}

	NpcTypes[51] = &NpcType{
		ID: 51, Name: "CP-Aresden", SpriteType: 51,
		HP: 5000, MinDamage: 10, MaxDamage: 140,
		Defense: 50, DEX: 500, XP: 2222,
		AggroRange: 9, MoveSpeed: 1600, AttackSpeed: 1600, WanderRange: 0,
		DiceThrow: 10, DiceRange: 14,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 9,
		RespawnDelay: 10 * time.Second,
	}

	NpcTypes[70] = &NpcType{
		ID: 70, Name: "Dragon", SpriteType: 70,
		HP: 1950, MinDamage: 10, MaxDamage: 80,
		Defense: 460, DEX: 300, XP: 5250,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 10, DiceRange: 8,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 2,
		RespawnDelay: 10 * time.Second,
		INT: 70,
		Mana: 4000, MaxMana: 4000,
		MagicHitRatio: 250,
	}

	NpcTypes[82] = &NpcType{
		ID: 82, Name: "Sor-Aresden", SpriteType: 82,
		HP: 2000, MinDamage: 8, MaxDamage: 80,
		Defense: 300, DEX: 1000, XP: 2222,
		AggroRange: 7, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 8, DiceRange: 10,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 6,
		RespawnDelay: 60 * time.Second,
		INT: 70,
		Mana: 19000, MaxMana: 19000,
		MagicHitRatio: 9,
	}

	NpcTypes[83] = &NpcType{
		ID: 83, Name: "ATK-Aresden", SpriteType: 83,
		HP: 4000, MinDamage: 10, MaxDamage: 100,
		Defense: 400, DEX: 400, XP: 2222,
		AggroRange: 7, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 8,
		DiceThrow: 10, DiceRange: 10,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 3,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[84] = &NpcType{
		ID: 84, Name: "Elf-Aresden", SpriteType: 84,
		HP: 2000, MinDamage: 6, MaxDamage: 60,
		Defense: 300, DEX: 500, XP: 2222,
		AggroRange: 7, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 6, DiceRange: 10,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 8,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[85] = &NpcType{
		ID: 85, Name: "DSK-Aresden", SpriteType: 85,
		HP: 3000, MinDamage: 9, MaxDamage: 90,
		Defense: 500, DEX: 500, XP: 2222,
		AggroRange: 9, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 9, DiceRange: 10,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 4,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[86] = &NpcType{
		ID: 86, Name: "HBT-Aresden", SpriteType: 86,
		HP: 3000, MinDamage: 15, MaxDamage: 150,
		Defense: 100, DEX: 400, XP: 2222,
		AggroRange: 9, MoveSpeed: 1200, AttackSpeed: 1200, WanderRange: 8,
		DiceThrow: 15, DiceRange: 10,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 9,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[87] = &NpcType{
		ID: 87, Name: "CT-Aresden", SpriteType: 87,
		HP: 8000, MinDamage: 8, MaxDamage: 80,
		Defense: 200, DEX: 500, XP: 2222,
		AggroRange: 8, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 0,
		DiceThrow: 8, DiceRange: 10,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 9,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[88] = &NpcType{
		ID: 88, Name: "Bar-Aresden", SpriteType: 88,
		HP: 5000, MinDamage: 12, MaxDamage: 120,
		Defense: 300, DEX: 400, XP: 2222,
		AggroRange: 7, MoveSpeed: 1200, AttackSpeed: 1200, WanderRange: 8,
		DiceThrow: 12, DiceRange: 10,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 2,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[89] = &NpcType{
		ID: 89, Name: "AGC-Aresden", SpriteType: 89,
		HP: 10000, MinDamage: 15, MaxDamage: 150,
		Defense: 200, DEX: 500, XP: 2222,
		AggroRange: 8, MoveSpeed: 1600, AttackSpeed: 1600, WanderRange: 0,
		DiceThrow: 15, DiceRange: 10,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 9,
		RespawnDelay: 3 * time.Second,
		BossType: 1,
	}

	NpcTypes[91] = &NpcType{
		ID: 91, Name: "gate-a", SpriteType: 91,
		HP: 40000, MinDamage: 1, MaxDamage: 0,
		Defense: 800, DEX: 100, XP: 1,
		AggroRange: 1, MoveSpeed: 1600, AttackSpeed: 1600, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 1,
		RespawnDelay: 3 * time.Second,
		BossType: 1,
	}

	NpcTypes[95] = &NpcType{
		ID: 95, Name: "Willowisp", SpriteType: 95,
		HP: 6000, MinDamage: 10, MaxDamage: 100,
		Defense: 450, DEX: 600, XP: 20000,
		AggroRange: 5, MoveSpeed: 200, AttackSpeed: 200, WanderRange: 8,
		DiceThrow: 10, DiceRange: 10,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 5,
		RespawnDelay: 2 * time.Second,
		INT: 90,
		Mana: 25000, MaxMana: 25000,
		MagicHitRatio: 250,
	}

	NpcTypes[96] = &NpcType{
		ID: 96, Name: "AirEl", SpriteType: 96,
		HP: 3000, MinDamage: 10, MaxDamage: 100,
		Defense: 400, DEX: 500, XP: 14000,
		AggroRange: 5, MoveSpeed: 200, AttackSpeed: 200, WanderRange: 8,
		DiceThrow: 10, DiceRange: 10,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 1 * time.Second,
		INT: 90,
		Mana: 5000, MaxMana: 5000,
		MagicHitRatio: 250,
	}

	NpcTypes[97] = &NpcType{
		ID: 97, Name: "FireEl", SpriteType: 97,
		HP: 3500, MinDamage: 10, MaxDamage: 100,
		Defense: 500, DEX: 400, XP: 14000,
		AggroRange: 5, MoveSpeed: 400, AttackSpeed: 400, WanderRange: 8,
		DiceThrow: 10, DiceRange: 10,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 1 * time.Second,
		INT: 70,
		Mana: 5000, MaxMana: 5000,
		MagicHitRatio: 250,
	}

	NpcTypes[99] = &NpcType{
		ID: 99, Name: "IceEl", SpriteType: 99,
		HP: 4000, MinDamage: 10, MaxDamage: 100,
		Defense: 450, DEX: 450, XP: 14000,
		AggroRange: 5, MoveSpeed: 300, AttackSpeed: 300, WanderRange: 8,
		DiceThrow: 10, DiceRange: 10,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 1 * time.Second,
		INT: 120,
		Mana: 5000, MaxMana: 5000,
		MagicHitRatio: 250,
	}

	NpcTypes[1000] = &NpcType{
		ID: 1000, Name: "Attack-Dummy", SpriteType: 34,
		HP: 100, MinDamage: 1, MaxDamage: 0,
		Defense: 15, DEX: 300, XP: 205,
		AggroRange: 7, MoveSpeed: 2100, AttackSpeed: 2100, WanderRange: 8,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeSmall, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1001] = &NpcType{
		ID: 1001, Name: "Orc-Mage", SpriteType: 14,
		HP: 120, MinDamage: 4, MaxDamage: 12,
		Defense: 70, DEX: 100, XP: 262,
		AggroRange: 6, MoveSpeed: 1500, AttackSpeed: 1500, WanderRange: 8,
		DiceThrow: 4, DiceRange: 3,
		Size: SizeMedium, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 5 * time.Second,
		CanFlee: true, FleeHPPct: 20,
		INT: 50,
		Mana: 150, MaxMana: 150,
		MagicHitRatio: 10,
	}

	NpcTypes[1002] = &NpcType{
		ID: 1002, Name: "Ballon", SpriteType: 49,
		HP: 30000, MinDamage: 15, MaxDamage: 150,
		Defense: 450, DEX: 500, XP: 10,
		AggroRange: 5, MoveSpeed: 300, AttackSpeed: 300, WanderRange: 8,
		DiceThrow: 15, DiceRange: 10,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 4,
		RespawnDelay: 5 * time.Second,
		BossType: 1,
		INT: 70,
	}

	NpcTypes[1003] = &NpcType{
		ID: 1003, Name: "BigHellclaw", SpriteType: 49,
		HP: 15000, MinDamage: 15, MaxDamage: 210,
		Defense: 550, DEX: 1000, XP: 45000,
		AggroRange: 7, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 15, DiceRange: 14,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 5,
		RespawnDelay: 60 * time.Second,
		BossType: 1,
		INT: 70,
	}

	NpcTypes[1004] = &NpcType{
		ID: 1004, Name: "BigTigerworm", SpriteType: 50,
		HP: 25000, MinDamage: 18, MaxDamage: 306,
		Defense: 550, DEX: 1200, XP: 90000,
		AggroRange: 7, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 18, DiceRange: 17,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 6,
		RespawnDelay: 60 * time.Second,
		BossType: 1,
		INT: 90,
		Mana: 16000, MaxMana: 16000,
		MagicHitRatio: 300,
	}

	NpcTypes[1005] = &NpcType{
		ID: 1005, Name: "BigWyvern", SpriteType: 66,
		HP: 30000, MinDamage: 20, MaxDamage: 360,
		Defense: 550, DEX: 1000, XP: 45000,
		AggroRange: 8, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 20, DiceRange: 18,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 7,
		RespawnDelay: 60 * time.Second,
		BossType: 1,
		INT: 120,
		Mana: 16000, MaxMana: 16000,
		MagicHitRatio: 250,
	}

	NpcTypes[1006] = &NpcType{
		ID: 1006, Name: "BigFire-Wyvern", SpriteType: 73,
		HP: 40000, MinDamage: 20, MaxDamage: 360,
		Defense: 550, DEX: 1000, XP: 225000,
		AggroRange: 8, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 20, DiceRange: 18,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 7,
		RespawnDelay: 60 * time.Second,
		BossType: 1,
		INT: 70,
		Mana: 16000, MaxMana: 16000,
		MagicHitRatio: 250,
	}

	NpcTypes[1007] = &NpcType{
		ID: 1007, Name: "ApocHellclaw", SpriteType: 49,
		HP: 10000, MinDamage: 15, MaxDamage: 210,
		Defense: 400, DEX: 600, XP: 22500,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 15, DiceRange: 14,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 5,
		RespawnDelay: 60 * time.Second,
		BossType: 1,
		INT: 70,
	}

	NpcTypes[1008] = &NpcType{
		ID: 1008, Name: "ApocTigerworm", SpriteType: 50,
		HP: 17500, MinDamage: 18, MaxDamage: 306,
		Defense: 500, DEX: 800, XP: 60000,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 18, DiceRange: 17,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 6,
		RespawnDelay: 60 * time.Second,
		BossType: 1,
		INT: 90,
		Mana: 16000, MaxMana: 16000,
		MagicHitRatio: 250,
	}

	NpcTypes[1009] = &NpcType{
		ID: 1009, Name: "ApocWyvern", SpriteType: 66,
		HP: 25000, MinDamage: 20, MaxDamage: 360,
		Defense: 300, DEX: 300, XP: 30000,
		AggroRange: 8, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 20, DiceRange: 18,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 7,
		RespawnDelay: 60 * time.Second,
		BossType: 1,
		INT: 120,
		Mana: 16000, MaxMana: 16000,
		MagicHitRatio: 250,
	}

	NpcTypes[1010] = &NpcType{
		ID: 1010, Name: "ApocFire-Wyvern", SpriteType: 73,
		HP: 30000, MinDamage: 20, MaxDamage: 360,
		Defense: 300, DEX: 300, XP: 150000,
		AggroRange: 8, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 20, DiceRange: 18,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 7,
		RespawnDelay: 60 * time.Second,
		BossType: 1,
		INT: 70,
		Mana: 16000, MaxMana: 16000,
		MagicHitRatio: 250,
	}

	NpcTypes[1011] = &NpcType{
		ID: 1011, Name: "ApocAbaddon", SpriteType: 81,
		HP: 100000, MinDamage: 20, MaxDamage: 400,
		Defense: 80, DEX: 90, XP: 745000,
		AggroRange: 8, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 20, DiceRange: 20,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 7,
		RespawnDelay: 60 * time.Second,
		BossType: 1,
		INT: 130,
		Mana: 20000, MaxMana: 20000,
		MagicHitRatio: 300,
	}

	NpcTypes[1012] = &NpcType{
		ID: 1012, Name: "ES", SpriteType: 35,
		HP: 100, MinDamage: 1, MaxDamage: 0,
		Defense: 10, DEX: 10, XP: 3749,
		AggroRange: 7, MoveSpeed: 60000, AttackSpeed: 60000, WanderRange: 8,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeSmall, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 1 * time.Second,
		MagicHitRatio: 200,
	}

	NpcTypes[1013] = &NpcType{
		ID: 1013, Name: "Guard-Aresden", SpriteType: 21,
		HP: 1550, MinDamage: 3, MaxDamage: 24,
		Defense: 150, DEX: 330, XP: 1,
		AggroRange: 8, MoveSpeed: 1000, AttackSpeed: 1000, WanderRange: 8,
		DiceThrow: 3, DiceRange: 8,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 5,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 20,
		Mana: 1000, MaxMana: 1000,
		MagicHitRatio: 130,
	}

	NpcTypes[1014] = &NpcType{
		ID: 1014, Name: "Guard-Elvine", SpriteType: 21,
		HP: 1550, MinDamage: 3, MaxDamage: 24,
		Defense: 150, DEX: 330, XP: 1,
		AggroRange: 8, MoveSpeed: 1000, AttackSpeed: 1000, WanderRange: 8,
		DiceThrow: 3, DiceRange: 8,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 5,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 20,
		Mana: 1000, MaxMana: 1000,
		MagicHitRatio: 130,
	}

	NpcTypes[1015] = &NpcType{
		ID: 1015, Name: "Guard-Neutral", SpriteType: 21,
		HP: 1150, MinDamage: 3, MaxDamage: 24,
		Defense: 150, DEX: 330, XP: 1,
		AggroRange: 8, MoveSpeed: 1000, AttackSpeed: 1000, WanderRange: 8,
		DiceThrow: 3, DiceRange: 8,
		Size: SizeLarge, Side: SideNeutral,
		AttackRange: 5,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 20,
		Mana: 1000, MaxMana: 1000,
		MagicHitRatio: 130,
	}

	NpcTypes[1016] = &NpcType{
		ID: 1016, Name: "AGT-Elvine", SpriteType: 36,
		HP: 5000, MinDamage: 5, MaxDamage: 40,
		Defense: 50, DEX: 500, XP: 4000,
		AggroRange: 8, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 0,
		DiceThrow: 5, DiceRange: 8,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1017] = &NpcType{
		ID: 1017, Name: "CGT-Elvine", SpriteType: 37,
		HP: 5000, MinDamage: 10, MaxDamage: 140,
		Defense: 50, DEX: 500, XP: 4000,
		AggroRange: 8, MoveSpeed: 1800, AttackSpeed: 1800, WanderRange: 0,
		DiceThrow: 10, DiceRange: 14,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1018] = &NpcType{
		ID: 1018, Name: "MS-Elvine", SpriteType: 38,
		HP: 5000, MinDamage: 1, MaxDamage: 0,
		Defense: 50, DEX: 500, XP: 1000,
		AggroRange: 8, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1019] = &NpcType{
		ID: 1019, Name: "DT-Elvine", SpriteType: 39,
		HP: 5000, MinDamage: 1, MaxDamage: 0,
		Defense: 50, DEX: 500, XP: 1000,
		AggroRange: 8, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1020] = &NpcType{
		ID: 1020, Name: "ESG-Elvine", SpriteType: 40,
		HP: 8000, MinDamage: 1, MaxDamage: 0,
		Defense: 50, DEX: 500, XP: 1000,
		AggroRange: 8, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1021] = &NpcType{
		ID: 1021, Name: "GMG-Elvine", SpriteType: 41,
		HP: 500000, MinDamage: 1, MaxDamage: 0,
		Defense: 5000, DEX: 500, XP: 55450,
		AggroRange: 8, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
		BossType: 1,
		Mana: 80, MaxMana: 80,
	}

	NpcTypes[1022] = &NpcType{
		ID: 1022, Name: "LWB-Elvine", SpriteType: 43,
		HP: 2500, MinDamage: 10, MaxDamage: 50,
		Defense: 450, DEX: 500, XP: 6000,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 10, DiceRange: 5,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 8,
		RespawnDelay: 60 * time.Second,
		CanFlee: true, FleeHPPct: 10,
		INT: 70,
	}

	NpcTypes[1023] = &NpcType{
		ID: 1023, Name: "CP-Elvine", SpriteType: 51,
		HP: 5000, MinDamage: 10, MaxDamage: 140,
		Defense: 50, DEX: 500, XP: 2222,
		AggroRange: 9, MoveSpeed: 1600, AttackSpeed: 1600, WanderRange: 0,
		DiceThrow: 10, DiceRange: 14,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 9,
		RespawnDelay: 10 * time.Second,
	}

	NpcTypes[1024] = &NpcType{
		ID: 1024, Name: "XB-Elvine", SpriteType: 1,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1025] = &NpcType{
		ID: 1025, Name: "XW-Elvine", SpriteType: 2,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1026] = &NpcType{
		ID: 1026, Name: "XY-Elvine", SpriteType: 3,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1027] = &NpcType{
		ID: 1027, Name: "YB-Elvine", SpriteType: 4,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1028] = &NpcType{
		ID: 1028, Name: "YW-Elvine", SpriteType: 5,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1029] = &NpcType{
		ID: 1029, Name: "YY-Elvine", SpriteType: 6,
		HP: 850, MinDamage: 8, MaxDamage: 40,
		Defense: 150, DEX: 200, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1030] = &NpcType{
		ID: 1030, Name: "Sor-Elvine", SpriteType: 82,
		HP: 2000, MinDamage: 8, MaxDamage: 80,
		Defense: 300, DEX: 1000, XP: 2222,
		AggroRange: 7, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 8, DiceRange: 10,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 6,
		RespawnDelay: 60 * time.Second,
		INT: 70,
		Mana: 19000, MaxMana: 19000,
		MagicHitRatio: 9,
	}

	NpcTypes[1031] = &NpcType{
		ID: 1031, Name: "Elf-Elvine", SpriteType: 84,
		HP: 2000, MinDamage: 6, MaxDamage: 60,
		Defense: 300, DEX: 500, XP: 2222,
		AggroRange: 7, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 6, DiceRange: 10,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 8,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[1032] = &NpcType{
		ID: 1032, Name: "DSK-Elvine", SpriteType: 85,
		HP: 3000, MinDamage: 9, MaxDamage: 90,
		Defense: 500, DEX: 500, XP: 2222,
		AggroRange: 9, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 9, DiceRange: 10,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 4,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[1033] = &NpcType{
		ID: 1033, Name: "ATK-Elvine", SpriteType: 83,
		HP: 4000, MinDamage: 10, MaxDamage: 100,
		Defense: 400, DEX: 400, XP: 2222,
		AggroRange: 7, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 8,
		DiceThrow: 10, DiceRange: 10,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 3,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[1034] = &NpcType{
		ID: 1034, Name: "Bar-Elvine", SpriteType: 88,
		HP: 5000, MinDamage: 12, MaxDamage: 120,
		Defense: 300, DEX: 400, XP: 2222,
		AggroRange: 7, MoveSpeed: 1200, AttackSpeed: 1200, WanderRange: 8,
		DiceThrow: 12, DiceRange: 10,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 2,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[1035] = &NpcType{
		ID: 1035, Name: "HBT-Elvine", SpriteType: 86,
		HP: 3000, MinDamage: 15, MaxDamage: 150,
		Defense: 100, DEX: 400, XP: 2222,
		AggroRange: 9, MoveSpeed: 1200, AttackSpeed: 1200, WanderRange: 8,
		DiceThrow: 15, DiceRange: 10,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 9,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[1036] = &NpcType{
		ID: 1036, Name: "CT-Elvine", SpriteType: 87,
		HP: 8000, MinDamage: 8, MaxDamage: 80,
		Defense: 200, DEX: 500, XP: 2222,
		AggroRange: 8, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 0,
		DiceThrow: 8, DiceRange: 10,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 9,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1037] = &NpcType{
		ID: 1037, Name: "AGC-Elvine", SpriteType: 89,
		HP: 10000, MinDamage: 15, MaxDamage: 150,
		Defense: 200, DEX: 500, XP: 2222,
		AggroRange: 8, MoveSpeed: 1600, AttackSpeed: 1600, WanderRange: 0,
		DiceThrow: 15, DiceRange: 10,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 9,
		RespawnDelay: 3 * time.Second,
		BossType: 1,
	}

	NpcTypes[1038] = &NpcType{
		ID: 1038, Name: "gate-e", SpriteType: 91,
		HP: 40000, MinDamage: 1, MaxDamage: 0,
		Defense: 800, DEX: 100, XP: 1,
		AggroRange: 1, MoveSpeed: 1600, AttackSpeed: 1600, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 1,
		RespawnDelay: 3 * time.Second,
		BossType: 1,
	}

	NpcTypes[1039] = &NpcType{
		ID: 1039, Name: "Evil-DT", SpriteType: 39,
		HP: 5000, MinDamage: 1, MaxDamage: 0,
		Defense: 50, DEX: 500, XP: 1045,
		AggroRange: 8, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1040] = &NpcType{
		ID: 1040, Name: "Evil-AGT", SpriteType: 36,
		HP: 5000, MinDamage: 5, MaxDamage: 40,
		Defense: 50, DEX: 500, XP: 4000,
		AggroRange: 8, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 0,
		DiceThrow: 5, DiceRange: 8,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1041] = &NpcType{
		ID: 1041, Name: "Evil-CGT", SpriteType: 37,
		HP: 5000, MinDamage: 10, MaxDamage: 140,
		Defense: 50, DEX: 500, XP: 4000,
		AggroRange: 8, MoveSpeed: 1800, AttackSpeed: 1800, WanderRange: 0,
		DiceThrow: 10, DiceRange: 14,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
	}

	NpcTypes[1042] = &NpcType{
		ID: 1042, Name: "Evil-GHK", SpriteType: 44,
		HP: 3500, MinDamage: 10, MaxDamage: 90,
		Defense: 450, DEX: 500, XP: 8000,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 10, DiceRange: 9,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 4,
		RespawnDelay: 60 * time.Second,
		CanFlee: true, FleeHPPct: 10,
		INT: 70,
	}

	NpcTypes[1043] = &NpcType{
		ID: 1043, Name: "Evil-TK", SpriteType: 46,
		HP: 3500, MinDamage: 10, MaxDamage: 90,
		Defense: 450, DEX: 500, XP: 8000,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 10, DiceRange: 9,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 4,
		RespawnDelay: 60 * time.Second,
		CanFlee: true, FleeHPPct: 10,
		INT: 70,
	}

	NpcTypes[1044] = &NpcType{
		ID: 1044, Name: "Evil-GHKABS", SpriteType: 45,
		HP: 8000, MinDamage: 13, MaxDamage: 156,
		Defense: 450, DEX: 1000, XP: 20000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 13, DiceRange: 12,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 5,
		RespawnDelay: 60 * time.Second,
		INT: 70,
	}

	NpcTypes[1045] = &NpcType{
		ID: 1045, Name: "Evil-BG", SpriteType: 47,
		HP: 8000, MinDamage: 13, MaxDamage: 156,
		Defense: 450, DEX: 1000, XP: 20000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 13, DiceRange: 12,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 5,
		RespawnDelay: 60 * time.Second,
		INT: 70,
	}

	NpcTypes[1046] = &NpcType{
		ID: 1046, Name: "Evil-LWB", SpriteType: 43,
		HP: 2500, MinDamage: 10, MaxDamage: 50,
		Defense: 450, DEX: 500, XP: 6000,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 10, DiceRange: 5,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 8,
		RespawnDelay: 60 * time.Second,
		CanFlee: true, FleeHPPct: 10,
		INT: 70,
	}

	NpcTypes[1047] = &NpcType{
		ID: 1047, Name: "Evil-Sorceress", SpriteType: 82,
		HP: 3000, MinDamage: 11, MaxDamage: 110,
		Defense: 450, DEX: 1000, XP: 13500,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 11, DiceRange: 10,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 6,
		RespawnDelay: 60 * time.Second,
		INT: 70,
		Mana: 19000, MaxMana: 19000,
		MagicHitRatio: 9,
	}

	NpcTypes[1048] = &NpcType{
		ID: 1048, Name: "Evil-ATK", SpriteType: 83,
		HP: 8000, MinDamage: 13, MaxDamage: 156,
		Defense: 500, DEX: 1000, XP: 30000,
		AggroRange: 7, MoveSpeed: 1000, AttackSpeed: 1000, WanderRange: 8,
		DiceThrow: 13, DiceRange: 12,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 3,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[1049] = &NpcType{
		ID: 1049, Name: "Evil-Elf", SpriteType: 84,
		HP: 2500, MinDamage: 10, MaxDamage: 60,
		Defense: 450, DEX: 500, XP: 11250,
		AggroRange: 8, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 10, DiceRange: 6,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 8,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[1050] = &NpcType{
		ID: 1050, Name: "Evil-DSK", SpriteType: 85,
		HP: 5000, MinDamage: 10, MaxDamage: 90,
		Defense: 400, DEX: 600, XP: 13500,
		AggroRange: 6, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 8,
		DiceThrow: 10, DiceRange: 9,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 4,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[1051] = &NpcType{
		ID: 1051, Name: "Evil-Barbarian", SpriteType: 88,
		HP: 3500, MinDamage: 15, MaxDamage: 180,
		Defense: 500, DEX: 1000, XP: 11250,
		AggroRange: 7, MoveSpeed: 1400, AttackSpeed: 1400, WanderRange: 8,
		DiceThrow: 15, DiceRange: 12,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 2,
		RespawnDelay: 60 * time.Second,
	}

	NpcTypes[1052] = &NpcType{
		ID: 1052, Name: "Evil-ManaStone", SpriteType: 42,
		HP: 50000, MinDamage: 1, MaxDamage: 0,
		Defense: 1000, DEX: 500, XP: 1,
		AggroRange: 8, MoveSpeed: 500, AttackSpeed: 500, WanderRange: 0,
		DiceThrow: 0, DiceRange: 0,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 8,
		RespawnDelay: 3 * time.Second,
		BossType: 1,
	}

	NpcTypes[1053] = &NpcType{
		ID: 1053, Name: "Evil-DD", SpriteType: 31,
		HP: 3400, MinDamage: 10, MaxDamage: 100,
		Defense: 450, DEX: 500, XP: 14450,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 10, DiceRange: 10,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 4,
		RespawnDelay: 60 * time.Second,
		INT: 70,
		Mana: 2000, MaxMana: 2000,
		MagicHitRatio: 250,
	}

	NpcTypes[1054] = &NpcType{
		ID: 1054, Name: "Evil-GG", SpriteType: 52,
		HP: 5500, MinDamage: 15, MaxDamage: 150,
		Defense: 450, DEX: 500, XP: 21000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 15, DiceRange: 10,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 5,
		RespawnDelay: 60 * time.Second,
		INT: 70,
		Mana: 2000, MaxMana: 2000,
		MagicHitRatio: 250,
	}

	NpcTypes[1055] = &NpcType{
		ID: 1055, Name: "Guard-Equi", SpriteType: 21,
		HP: 1550, MinDamage: 3, MaxDamage: 24,
		Defense: 150, DEX: 330, XP: 1,
		AggroRange: 8, MoveSpeed: 1000, AttackSpeed: 1000, WanderRange: 8,
		DiceThrow: 3, DiceRange: 8,
		Size: SizeLarge, Side: SideSpecial,
		AttackRange: 5,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 20,
		Mana: 1000, MaxMana: 1000,
		MagicHitRatio: 130,
	}

	NpcTypes[1056] = &NpcType{
		ID: 1056, Name: "Hellcat", SpriteType: 56,
		HP: 800, MinDamage: 6, MaxDamage: 24,
		Defense: 200, DEX: 300, XP: 1225,
		AggroRange: 6, MoveSpeed: 1500, AttackSpeed: 1500, WanderRange: 8,
		DiceThrow: 6, DiceRange: 4,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 20 * time.Second,
		INT: 70,
		Mana: 800, MaxMana: 800,
		MagicHitRatio: 100,
	}

	NpcTypes[1057] = &NpcType{
		ID: 1057, Name: "City-Cyclops", SpriteType: 13,
		HP: 800, MinDamage: 10, MaxDamage: 60,
		Defense: 120, DEX: 200, XP: 630,
		AggroRange: 7, MoveSpeed: 1000, AttackSpeed: 1000, WanderRange: 8,
		DiceThrow: 10, DiceRange: 6,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 3,
		RespawnDelay: 20 * time.Second,
		INT: 50,
		Mana: 900, MaxMana: 900,
		MagicHitRatio: 50,
	}

	NpcTypes[1058] = &NpcType{
		ID: 1058, Name: "City-Ogre", SpriteType: 29,
		HP: 1350, MinDamage: 10, MaxDamage: 70,
		Defense: 170, DEX: 250, XP: 1225,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 10, DiceRange: 7,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 3,
		RespawnDelay: 20 * time.Second,
		INT: 70,
	}

	NpcTypes[1059] = &NpcType{
		ID: 1059, Name: "City-Dark-Elf", SpriteType: 54,
		HP: 1500, MinDamage: 8, MaxDamage: 32,
		Defense: 240, DEX: 450, XP: 1575,
		AggroRange: 8, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 4,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 6,
		RespawnDelay: 20 * time.Second,
		INT: 70,
	}

	NpcTypes[1060] = &NpcType{
		ID: 1060, Name: "War-Elvine", SpriteType: 2,
		HP: 1200, MinDamage: 8, MaxDamage: 40,
		Defense: 200, DEX: 250, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideElvine,
		AttackRange: 3,
		RespawnDelay: 30 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1061] = &NpcType{
		ID: 1061, Name: "War-Aresden", SpriteType: 2,
		HP: 1200, MinDamage: 8, MaxDamage: 40,
		Defense: 200, DEX: 250, XP: 2000,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideAresden,
		AttackRange: 3,
		RespawnDelay: 30 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1062] = &NpcType{
		ID: 1062, Name: "City-Stone-Golem", SpriteType: 12,
		HP: 250, MinDamage: 7, MaxDamage: 28,
		Defense: 110, DEX: 150, XP: 542,
		AggroRange: 5, MoveSpeed: 1200, AttackSpeed: 1200, WanderRange: 8,
		DiceThrow: 7, DiceRange: 4,
		Size: SizeMedium, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 10 * time.Second,
	}

	NpcTypes[1063] = &NpcType{
		ID: 1063, Name: "CrimM1", SpriteType: 3,
		HP: 900, MinDamage: 5, MaxDamage: 30,
		Defense: 150, DEX: 130, XP: 2800,
		AggroRange: 5, MoveSpeed: 1000, AttackSpeed: 1000, WanderRange: 8,
		DiceThrow: 5, DiceRange: 6,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1064] = &NpcType{
		ID: 1064, Name: "CrimF1", SpriteType: 6,
		HP: 850, MinDamage: 5, MaxDamage: 25,
		Defense: 190, DEX: 160, XP: 2800,
		AggroRange: 5, MoveSpeed: 1000, AttackSpeed: 1000, WanderRange: 8,
		DiceThrow: 5, DiceRange: 5,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1065] = &NpcType{
		ID: 1065, Name: "CrimM2", SpriteType: 1,
		HP: 1200, MinDamage: 8, MaxDamage: 48,
		Defense: 150, DEX: 250, XP: 3500,
		AggroRange: 6, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 8,
		DiceThrow: 8, DiceRange: 6,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 2,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1066] = &NpcType{
		ID: 1066, Name: "CrimF2", SpriteType: 4,
		HP: 1100, MinDamage: 8, MaxDamage: 40,
		Defense: 210, DEX: 210, XP: 3500,
		AggroRange: 6, MoveSpeed: 800, AttackSpeed: 800, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 2,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1067] = &NpcType{
		ID: 1067, Name: "CrimM3", SpriteType: 2,
		HP: 1700, MinDamage: 11, MaxDamage: 66,
		Defense: 190, DEX: 280, XP: 5250,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 11, DiceRange: 6,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1068] = &NpcType{
		ID: 1068, Name: "CrimF3", SpriteType: 5,
		HP: 1500, MinDamage: 11, MaxDamage: 55,
		Defense: 230, DEX: 260, XP: 5250,
		AggroRange: 7, MoveSpeed: 600, AttackSpeed: 600, WanderRange: 8,
		DiceThrow: 11, DiceRange: 5,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		CanFlee: true, FleeHPPct: 10,
	}

	NpcTypes[1069] = &NpcType{
		ID: 1069, Name: "XPCyclops", SpriteType: 13,
		HP: 700, MinDamage: 8, MaxDamage: 48,
		Defense: 100, DEX: 180, XP: 200000,
		AggroRange: 7, MoveSpeed: 1200, AttackSpeed: 1200, WanderRange: 8,
		DiceThrow: 8, DiceRange: 6,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 3,
		RespawnDelay: 10 * time.Second,
		INT: 50,
		Mana: 450, MaxMana: 450,
		MagicHitRatio: 50,
	}

	NpcTypes[1070] = &NpcType{
		ID: 1070, Name: "XPTroll", SpriteType: 28,
		HP: 750, MinDamage: 8, MaxDamage: 40,
		Defense: 85, DEX: 200, XP: 200000,
		AggroRange: 7, MoveSpeed: 700, AttackSpeed: 700, WanderRange: 8,
		DiceThrow: 8, DiceRange: 5,
		Size: SizeLarge, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 10 * time.Second,
	}

	NpcTypes[1071] = &NpcType{
		ID: 1071, Name: "XPOrc", SpriteType: 14,
		HP: 170, MinDamage: 4, MaxDamage: 12,
		Defense: 70, DEX: 100, XP: 100000,
		AggroRange: 6, MoveSpeed: 1500, AttackSpeed: 1500, WanderRange: 8,
		DiceThrow: 4, DiceRange: 3,
		Size: SizeMedium, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 5 * time.Second,
		CanFlee: true, FleeHPPct: 20,
		INT: 50,
		Mana: 150, MaxMana: 150,
		MagicHitRatio: 10,
	}

	NpcTypes[1072] = &NpcType{
		ID: 1072, Name: "XPClay-Golem", SpriteType: 23,
		HP: 400, MinDamage: 7, MaxDamage: 28,
		Defense: 100, DEX: 150, XP: 100000,
		AggroRange: 5, MoveSpeed: 1200, AttackSpeed: 1200, WanderRange: 8,
		DiceThrow: 7, DiceRange: 4,
		Size: SizeMedium, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 10 * time.Second,
	}

	NpcTypes[1073] = &NpcType{
		ID: 1073, Name: "XPStone-Golem", SpriteType: 12,
		HP: 350, MinDamage: 7, MaxDamage: 28,
		Defense: 110, DEX: 150, XP: 100000,
		AggroRange: 5, MoveSpeed: 1200, AttackSpeed: 1200, WanderRange: 8,
		DiceThrow: 7, DiceRange: 4,
		Size: SizeMedium, Side: SideMonster,
		AttackRange: 1,
		RespawnDelay: 10 * time.Second,
	}

}
