// Code generated by tools/magicimport; DO NOT EDIT.
//
// Source: helbreath-v3.82-master/Server/Core/Magic.cfg
// Contains all 90 original Helbreath spells.
package magic

// initGeneratedSpells registers all spells parsed from the original Magic.cfg.
// Spells are only added if the ID is not already present in SpellDB,
// allowing hand-written definitions to take precedence.
func init() {
	if SpellDB[0] == nil {
		SpellDB[0] = &SpellDef{
			ID: 0, Name: "Magic Missile",
			Type: SpellTypeDamage, Element: ElementLight,
			ManaCost: 8, CastTime: 500, Cooldown: 2000, Range: 1,
			MinDamage: 1, MaxDamage: 8,
			ReqLevel: 1, ReqMAG: 18, ReqINT: 18,
			SpriteID: 0, SoundID: 5,
		}
	}

	if SpellDB[1] == nil {
		SpellDB[1] = &SpellDef{
			ID: 1, Name: "Heal",
			Type: SpellTypeHeal, Element: ElementIce,
			ManaCost: 15, CastTime: 500, Cooldown: 3000, Range: 0,
			HealAmount: 17,
			ReqLevel: 1, ReqMAG: 20, ReqINT: 20,
			SpriteID: 1, SoundID: 45,
		}
	}

	if SpellDB[2] == nil {
		SpellDB[2] = &SpellDef{
			ID: 2, Name: "Create Food",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 18, CastTime: 500, Cooldown: 10000, Range: 0,
			Duration: 60,
			ReqLevel: 1, ReqMAG: 18, ReqINT: 18,
			SpriteID: 2, SoundID: 1,
		}
	}

	if SpellDB[3] == nil {
		SpellDB[3] = &SpellDef{
			ID: 3, Name: "Abaddons terror",
			Type: SpellTypeAOE, Element: ElementLight,
			ManaCost: 10, CastTime: 500, Cooldown: 4000, Range: 3,
			Radius: 3,
			MinDamage: 1998, MaxDamage: 999000,
			ReqLevel: 35, ReqMAG: 301, ReqINT: 301,
			SpriteID: 3, SoundID: 5,
		}
	}

	if SpellDB[4] == nil {
		SpellDB[4] = &SpellDef{
			ID: 4, Name: "Abaddons fury",
			Type: SpellTypeAOE, Element: ElementNone,
			ManaCost: 10, CastTime: 500, Cooldown: 4000, Range: 255,
			Radius: 5,
			MinDamage: 37, MaxDamage: 79,
			ReqLevel: 35, ReqMAG: 301, ReqINT: 301,
			SpriteID: 4, SoundID: 1,
		}
	}

	if SpellDB[5] == nil {
		SpellDB[5] = &SpellDef{
			ID: 5, Name: "Ultimate Elixir",
			Type: SpellTypeAOE, Element: ElementEarth,
			ManaCost: 70, CastTime: 1100, Cooldown: 4000, Range: 5,
			Radius: 5,
			MinDamage: 16, MaxDamage: 28,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 5, SoundID: 7,
		}
	}

	if SpellDB[6] == nil {
		SpellDB[6] = &SpellDef{
			ID: 6, Name: "Forge's Breath",
			Type: SpellTypeDamage, Element: ElementFire,
			ManaCost: 70, CastTime: 1100, Cooldown: 2000, Range: 2,
			MinDamage: 44, MaxDamage: 84,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 6, SoundID: 4,
		}
	}

	if SpellDB[10] == nil {
		SpellDB[10] = &SpellDef{
			ID: 10, Name: "Energy Bolt",
			Type: SpellTypeDamage, Element: ElementLight,
			ManaCost: 15, CastTime: 500, Cooldown: 2000, Range: 2,
			MinDamage: 6, MaxDamage: 18,
			ReqLevel: 5, ReqMAG: 24, ReqINT: 24,
			SpriteID: 10, SoundID: 5,
		}
	}

	if SpellDB[11] == nil {
		SpellDB[11] = &SpellDef{
			ID: 11, Name: "Staminar Drain",
			Type: SpellTypeDamage, Element: ElementNone,
			ManaCost: 14, CastTime: 500, Cooldown: 2000, Range: 3,
			MinDamage: 41, MaxDamage: 71,
			ReqLevel: 5, ReqMAG: 22, ReqINT: 22,
			SpriteID: 11, SoundID: 1,
		}
	}

	if SpellDB[12] == nil {
		SpellDB[12] = &SpellDef{
			ID: 12, Name: "Recall",
			Type: SpellTypeTeleport, Element: ElementNone,
			ManaCost: 15, CastTime: 500, Cooldown: 60000, Range: 0,
			ReqLevel: 1, ReqMAG: 20, ReqINT: 20,
			SpriteID: 12, SoundID: 1,
		}
	}

	if SpellDB[13] == nil {
		SpellDB[13] = &SpellDef{
			ID: 13, Name: "Defense Shield",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 19, CastTime: 500, Cooldown: 10000, Range: 0,
			Duration: 60,
			BuffStat: 2, BuffAmount: 5,
			ReqLevel: 5, ReqMAG: 26, ReqINT: 26,
			SpriteID: 13, SoundID: 1,
			ApplyEffect: EffectMagicProtection, EffectLevel: 3,
		}
	}

	if SpellDB[14] == nil {
		SpellDB[14] = &SpellDef{
			ID: 14, Name: "Celebrating Light",
			Type: SpellTypeDamage, Element: ElementNone,
			ManaCost: 20, CastTime: 500, Cooldown: 2000, Range: 1,
			ReqLevel: 5, ReqMAG: 25, ReqINT: 25,
			SpriteID: 14, SoundID: 1,
		}
	}

	if SpellDB[15] == nil {
		SpellDB[15] = &SpellDef{
			ID: 15, Name: "Staminar Recovery",
			Type: SpellTypeHeal, Element: ElementNone,
			ManaCost: 20, CastTime: 500, Cooldown: 3000, Range: 2,
			HealAmount: 38,
			ReqLevel: 1, ReqMAG: 20, ReqINT: 20,
			SpriteID: 15, SoundID: 45,
		}
	}

	if SpellDB[16] == nil {
		SpellDB[16] = &SpellDef{
			ID: 16, Name: "Peace",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 77, CastTime: 1100, Cooldown: 10000, Range: 0,
			Duration: 60,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 16, SoundID: 1,
		}
	}

	if SpellDB[17] == nil {
		SpellDB[17] = &SpellDef{
			ID: 17, Name: "Wood Mantle",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 44, CastTime: 900, Cooldown: 180000, Range: 0,
			Duration: 60,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 17, SoundID: 1,
			ApplyEffect: EffectDefenseShield, EffectLevel: 1,
		}
	}

	if SpellDB[20] == nil {
		SpellDB[20] = &SpellDef{
			ID: 20, Name: "Fire Ball",
			Type: SpellTypeDamage, Element: ElementFire,
			ManaCost: 27, CastTime: 700, Cooldown: 2000, Range: 2,
			MinDamage: 8, MaxDamage: 28,
			ReqLevel: 5, ReqMAG: 26, ReqINT: 26,
			SpriteID: 20, SoundID: 4,
		}
	}

	if SpellDB[21] == nil {
		SpellDB[21] = &SpellDef{
			ID: 21, Name: "Great Heal",
			Type: SpellTypeHeal, Element: ElementNone,
			ManaCost: 28, CastTime: 700, Cooldown: 3000, Range: 0,
			HealAmount: 42,
			ReqLevel: 5, ReqMAG: 28, ReqINT: 28,
			SpriteID: 21, SoundID: 45,
		}
	}

	if SpellDB[22] == nil {
		SpellDB[22] = &SpellDef{
			ID: 22, Name: "Tremor",
			Type: SpellTypeAOE, Element: ElementEarth,
			ManaCost: 34, CastTime: 700, Cooldown: 4000, Range: 2,
			Radius: 2,
			MinDamage: 15, MaxDamage: 33,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 22, SoundID: 7,
		}
	}

	if SpellDB[23] == nil {
		SpellDB[23] = &SpellDef{
			ID: 23, Name: "Great Staminar Recovery",
			Type: SpellTypeHeal, Element: ElementNone,
			ManaCost: 45, CastTime: 900, Cooldown: 3000, Range: 3,
			HealAmount: 73,
			ReqLevel: 5, ReqMAG: 30, ReqINT: 30,
			SpriteID: 23, SoundID: 45,
		}
	}

	if SpellDB[24] == nil {
		SpellDB[24] = &SpellDef{
			ID: 24, Name: "Protection From Arrow",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 22, CastTime: 700, Cooldown: 10000, Range: 0,
			Duration: 60,
			ReqLevel: 1, ReqMAG: 20, ReqINT: 20,
			SpriteID: 24, SoundID: 1,
			ApplyEffect: EffectDefenseShield, EffectLevel: 1,
		}
	}

	if SpellDB[25] == nil {
		SpellDB[25] = &SpellDef{
			ID: 25, Name: "Hold Person",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 24, CastTime: 700, Cooldown: 8000, Range: 1,
			Duration: 30,
			BuffStat: 3, BuffAmount: -5,
			ReqLevel: 5, ReqMAG: 26, ReqINT: 26,
			SpriteID: 25, SoundID: 1,
			ApplyEffect: EffectIce, EffectLevel: 1,
		}
	}

	if SpellDB[26] == nil {
		SpellDB[26] = &SpellDef{
			ID: 26, Name: "Possession",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 25, CastTime: 700, Cooldown: 8000, Range: 1,
			Duration: 30,
			ReqLevel: 5, ReqMAG: 26, ReqINT: 26,
			SpriteID: 26, SoundID: 1,
		}
	}

	if SpellDB[27] == nil {
		SpellDB[27] = &SpellDef{
			ID: 27, Name: "Poison",
			Type: SpellTypeDebuff, Element: ElementEarth,
			ManaCost: 28, CastTime: 700, Cooldown: 8000, Range: 1,
			Duration: 30,
			ReqLevel: 5, ReqMAG: 29, ReqINT: 29,
			SpriteID: 27, SoundID: 7,
			ApplyEffect: EffectPoison, EffectLevel: 1,
			TickDamage: 25, TickIntervalMs: 3000,
		}
	}

	if SpellDB[28] == nil {
		SpellDB[28] = &SpellDef{
			ID: 28, Name: "Mass Staminar Recov",
			Type: SpellTypeHeal, Element: ElementNone,
			ManaCost: 65, CastTime: 1100, Cooldown: 3000, Range: 4,
			HealAmount: 146,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 28, SoundID: 45,
		}
	}

	if SpellDB[30] == nil {
		SpellDB[30] = &SpellDef{
			ID: 30, Name: "Fire Strike",
			Type: SpellTypeDamage, Element: ElementFire,
			ManaCost: 36, CastTime: 700, Cooldown: 2000, Range: 2,
			MinDamage: 10, MaxDamage: 38,
			ReqLevel: 10, ReqMAG: 34, ReqINT: 34,
			SpriteID: 30, SoundID: 4,
		}
	}

	if SpellDB[31] == nil {
		SpellDB[31] = &SpellDef{
			ID: 31, Name: "Summon Creature",
			Type: SpellTypeSummon, Element: ElementEarth,
			ManaCost: 35, CastTime: 700, Cooldown: 30000, Range: 1,
			ReqLevel: 10, ReqMAG: 38, ReqINT: 38,
			SpriteID: 31, SoundID: 7,
		}
	}

	if SpellDB[32] == nil {
		SpellDB[32] = &SpellDef{
			ID: 32, Name: "Invisibility",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 31, CastTime: 700, Cooldown: 10000, Range: 0,
			Duration: 60,
			ReqLevel: 5, ReqMAG: 30, ReqINT: 30,
			SpriteID: 32, SoundID: 1,
			ApplyEffect: EffectInvisibility, EffectLevel: 1,
		}
	}

	if SpellDB[33] == nil {
		SpellDB[33] = &SpellDef{
			ID: 33, Name: "Protection From Magic",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 35, CastTime: 700, Cooldown: 10000, Range: 0,
			Duration: 60,
			ReqLevel: 10, ReqMAG: 32, ReqINT: 32,
			SpriteID: 33, SoundID: 1,
			ApplyEffect: EffectMagicProtection, EffectLevel: 2,
		}
	}

	if SpellDB[34] == nil {
		SpellDB[34] = &SpellDef{
			ID: 34, Name: "Detect Invisibility",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 33, CastTime: 700, Cooldown: 10000, Range: 0,
			Duration: 60,
			ReqLevel: 5, ReqMAG: 30, ReqINT: 30,
			SpriteID: 34, SoundID: 1,
			ApplyEffect: EffectInvisibility, EffectLevel: 2,
		}
	}

	if SpellDB[35] == nil {
		SpellDB[35] = &SpellDef{
			ID: 35, Name: "Paralyze",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 35, CastTime: 700, Cooldown: 8000, Range: 1,
			Duration: 50,
			BuffStat: 3, BuffAmount: -10,
			ReqLevel: 10, ReqMAG: 36, ReqINT: 36,
			SpriteID: 35, SoundID: 1,
			ApplyEffect: EffectIce, EffectLevel: 2,
		}
	}

	if SpellDB[36] == nil {
		SpellDB[36] = &SpellDef{
			ID: 36, Name: "Cure",
			Type: SpellTypeHeal, Element: ElementEarth,
			ManaCost: 32, CastTime: 700, Cooldown: 3000, Range: 0,
			ReqLevel: 10, ReqMAG: 35, ReqINT: 35,
			SpriteID: 36, SoundID: 45,
		}
	}

	if SpellDB[37] == nil {
		SpellDB[37] = &SpellDef{
			ID: 37, Name: "Lightning Arrow",
			Type: SpellTypeDamage, Element: ElementLight,
			ManaCost: 32, CastTime: 700, Cooldown: 2000, Range: 1,
			MinDamage: 14, MaxDamage: 42,
			ReqLevel: 10, ReqMAG: 38, ReqINT: 38,
			SpriteID: 37, SoundID: 5,
		}
	}

	if SpellDB[38] == nil {
		SpellDB[38] = &SpellDef{
			ID: 38, Name: "Prayer",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 49, CastTime: 900, Cooldown: 10000, Range: 0,
			Duration: 40,
			BuffStat: 2, BuffAmount: 8,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 38, SoundID: 1,
		}
	}

	if SpellDB[40] == nil {
		SpellDB[40] = &SpellDef{
			ID: 40, Name: "Fire Wall",
			Type: SpellTypeAOE, Element: ElementFire,
			ManaCost: 42, CastTime: 900, Cooldown: 4000, Range: 1,
			Radius: 1,
			MinDamage: 7, MaxDamage: 35,
			Duration: 30,
			ReqLevel: 10, ReqMAG: 45, ReqINT: 45,
			SpriteID: 40, SoundID: 4,
		}
	}

	if SpellDB[41] == nil {
		SpellDB[41] = &SpellDef{
			ID: 41, Name: "Fire Field",
			Type: SpellTypeAOE, Element: ElementFire,
			ManaCost: 48, CastTime: 900, Cooldown: 4000, Range: 1,
			Radius: 1,
			MinDamage: 6, MaxDamage: 35,
			Duration: 30,
			ReqLevel: 10, ReqMAG: 48, ReqINT: 48,
			SpriteID: 41, SoundID: 4,
		}
	}

	if SpellDB[42] == nil {
		SpellDB[42] = &SpellDef{
			ID: 42, Name: "Confuse Language",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 40, CastTime: 700, Cooldown: 8000, Range: 1,
			Duration: 120,
			ReqLevel: 10, ReqMAG: 42, ReqINT: 42,
			SpriteID: 42, SoundID: 1,
			ApplyEffect: EffectConfusion, EffectLevel: 1,
		}
	}

	if SpellDB[43] == nil {
		SpellDB[43] = &SpellDef{
			ID: 43, Name: "Lightning",
			Type: SpellTypeDamage, Element: ElementLight,
			ManaCost: 44, CastTime: 900, Cooldown: 2000, Range: 1,
			MinDamage: 24, MaxDamage: 59,
			ReqLevel: 10, ReqMAG: 47, ReqINT: 47,
			SpriteID: 43, SoundID: 5,
		}
	}

	if SpellDB[44] == nil {
		SpellDB[44] = &SpellDef{
			ID: 44, Name: "Great Defense Shield",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 45, CastTime: 900, Cooldown: 10000, Range: 0,
			Duration: 60,
			BuffStat: 2, BuffAmount: 12,
			ReqLevel: 10, ReqMAG: 46, ReqINT: 46,
			SpriteID: 44, SoundID: 1,
			ApplyEffect: EffectMagicProtection, EffectLevel: 4,
		}
	}

	if SpellDB[45] == nil {
		SpellDB[45] = &SpellDef{
			ID: 45, Name: "Chill Wind",
			Type: SpellTypeAOE, Element: ElementIce,
			ManaCost: 48, CastTime: 900, Cooldown: 4000, Range: 3,
			Radius: 3,
			MinDamage: 6, MaxDamage: 27,
			ReqLevel: 10, ReqMAG: 50, ReqINT: 50,
			SpriteID: 45, SoundID: 46,
		}
	}

	if SpellDB[46] == nil {
		SpellDB[46] = &SpellDef{
			ID: 46, Name: "Poison Cloud",
			Type: SpellTypeAOE, Element: ElementEarth,
			ManaCost: 48, CastTime: 900, Cooldown: 4000, Range: 1,
			Radius: 1,
			MinDamage: 11, MaxDamage: 21,
			Duration: 30,
			ReqLevel: 10, ReqMAG: 49, ReqINT: 49,
			SpriteID: 46, SoundID: 7,
		}
	}

	if SpellDB[47] == nil {
		SpellDB[47] = &SpellDef{
			ID: 47, Name: "Triple Energy Bolt",
			Type: SpellTypeDamage, Element: ElementLight,
			ManaCost: 40, CastTime: 700, Cooldown: 2000, Range: 2,
			MinDamage: 10, MaxDamage: 37,
			ReqLevel: 10, ReqMAG: 45, ReqINT: 45,
			SpriteID: 47, SoundID: 5,
		}
	}

	if SpellDB[48] == nil {
		SpellDB[48] = &SpellDef{
			ID: 48, Name: "Critical Heal",
			Type: SpellTypeHeal, Element: ElementNone,
			ManaCost: 45, CastTime: 900, Cooldown: 3000, Range: 0,
			HealAmount: 94,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 48, SoundID: 45,
		}
	}

	if SpellDB[50] == nil {
		SpellDB[50] = &SpellDef{
			ID: 50, Name: "Berserk",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 57, CastTime: 900, Cooldown: 10000, Range: 0,
			Duration: 40,
			BuffStat: 1, BuffAmount: 10,
			ReqLevel: 15, ReqMAG: 59, ReqINT: 59,
			SpriteID: 50, SoundID: 1,
			ApplyEffect: EffectBerserk, EffectLevel: 1,
		}
	}

	if SpellDB[51] == nil {
		SpellDB[51] = &SpellDef{
			ID: 51, Name: "Lightning Bolt",
			Type: SpellTypeAOE, Element: ElementLight,
			ManaCost: 58, CastTime: 900, Cooldown: 4000, Range: 2,
			Radius: 2,
			MinDamage: 16, MaxDamage: 46,
			ReqLevel: 15, ReqMAG: 58, ReqINT: 58,
			SpriteID: 51, SoundID: 5,
		}
	}

	if SpellDB[52] == nil {
		SpellDB[52] = &SpellDef{
			ID: 52, Name: "Polymorph",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 66, CastTime: 1100, Cooldown: 10000, Range: 0,
			Duration: 60,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 52, SoundID: 1,
		}
	}

	if SpellDB[53] == nil {
		SpellDB[53] = &SpellDef{
			ID: 53, Name: "Mass Poison",
			Type: SpellTypeDebuff, Element: ElementEarth,
			ManaCost: 54, CastTime: 900, Cooldown: 8000, Range: 1,
			Duration: 30,
			ReqLevel: 15, ReqMAG: 52, ReqINT: 52,
			SpriteID: 53, SoundID: 7,
			ApplyEffect: EffectPoison, EffectLevel: 1,
			TickDamage: 60, TickIntervalMs: 3000,
		}
	}

	if SpellDB[54] == nil {
		SpellDB[54] = &SpellDef{
			ID: 54, Name: "Spike Field",
			Type: SpellTypeAOE, Element: ElementEarth,
			ManaCost: 56, CastTime: 900, Cooldown: 4000, Range: 1,
			Radius: 1,
			MinDamage: 15, MaxDamage: 52,
			Duration: 30,
			ReqLevel: 15, ReqMAG: 56, ReqINT: 56,
			SpriteID: 54, SoundID: 7,
		}
	}

	if SpellDB[55] == nil {
		SpellDB[55] = &SpellDef{
			ID: 55, Name: "Ice Storm",
			Type: SpellTypeAOE, Element: ElementIce,
			ManaCost: 58, CastTime: 900, Cooldown: 4000, Range: 1,
			Radius: 1,
			MinDamage: 8, MaxDamage: 8,
			Duration: 30,
			ReqLevel: 15, ReqMAG: 59, ReqINT: 59,
			SpriteID: 55, SoundID: 46,
		}
	}

	if SpellDB[56] == nil {
		SpellDB[56] = &SpellDef{
			ID: 56, Name: "Mass Lightning Arrow",
			Type: SpellTypeDamage, Element: ElementLight,
			ManaCost: 55, CastTime: 900, Cooldown: 2000, Range: 1,
			MinDamage: 24, MaxDamage: 59,
			ReqLevel: 15, ReqMAG: 53, ReqINT: 53,
			SpriteID: 56, SoundID: 5,
		}
	}

	if SpellDB[57] == nil {
		SpellDB[57] = &SpellDef{
			ID: 57, Name: "Ice Strike",
			Type: SpellTypeAOE, Element: ElementIce,
			ManaCost: 59, CastTime: 900, Cooldown: 4000, Range: 2,
			Radius: 2,
			MinDamage: 17, MaxDamage: 42,
			ReqLevel: 15, ReqMAG: 60, ReqINT: 60,
			SpriteID: 57, SoundID: 46,
		}
	}

	if SpellDB[58] == nil {
		SpellDB[58] = &SpellDef{
			ID: 58, Name: "Bloody Mantle",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 88, CastTime: 1100, Cooldown: 180000, Range: 0,
			Duration: 25,
			ReqLevel: 15, ReqMAG: 65, ReqINT: 65,
			SpriteID: 58, SoundID: 1,
			ApplyEffect: EffectDefenseShield, EffectLevel: 2,
		}
	}

	if SpellDB[60] == nil {
		SpellDB[60] = &SpellDef{
			ID: 60, Name: "Energy Strike",
			Type: SpellTypeAOE, Element: ElementLight,
			ManaCost: 65, CastTime: 1100, Cooldown: 4000, Range: 2,
			Radius: 2,
			MinDamage: 24, MaxDamage: 59,
			ReqLevel: 15, ReqMAG: 67, ReqINT: 67,
			SpriteID: 60, SoundID: 5,
		}
	}

	if SpellDB[61] == nil {
		SpellDB[61] = &SpellDef{
			ID: 61, Name: "Mass Fire Strike",
			Type: SpellTypeDamage, Element: ElementFire,
			ManaCost: 80, CastTime: 1100, Cooldown: 2000, Range: 2,
			MinDamage: 38, MaxDamage: 93,
			ReqLevel: 20, ReqMAG: 85, ReqINT: 85,
			SpriteID: 61, SoundID: 4,
		}
	}

	if SpellDB[62] == nil {
		SpellDB[62] = &SpellDef{
			ID: 62, Name: "Confusion",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 78, CastTime: 1100, Cooldown: 8000, Range: 2,
			Duration: 45,
			ReqLevel: 15, ReqMAG: 75, ReqINT: 75,
			SpriteID: 62, SoundID: 1,
			ApplyEffect: EffectConfusion, EffectLevel: 2,
		}
	}

	if SpellDB[63] == nil {
		SpellDB[63] = &SpellDef{
			ID: 63, Name: "Mass Chill Wind",
			Type: SpellTypeAOE, Element: ElementIce,
			ManaCost: 90, CastTime: 1100, Cooldown: 4000, Range: 3,
			Radius: 3,
			MinDamage: 24, MaxDamage: 59,
			ReqLevel: 20, ReqMAG: 93, ReqINT: 93,
			SpriteID: 63, SoundID: 46,
		}
	}

	if SpellDB[64] == nil {
		SpellDB[64] = &SpellDef{
			ID: 64, Name: "Earthworm Strike",
			Type: SpellTypeAOE, Element: ElementEarth,
			ManaCost: 80, CastTime: 1100, Cooldown: 4000, Range: 2,
			Radius: 2,
			MinDamage: 48, MaxDamage: 118,
			ReqLevel: 20, ReqMAG: 97, ReqINT: 97,
			SpriteID: 64, SoundID: 7,
		}
	}

	if SpellDB[65] == nil {
		SpellDB[65] = &SpellDef{
			ID: 65, Name: "Absolute Magic Protect",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 90, CastTime: 1100, Cooldown: 10000, Range: 0,
			Duration: 60,
			ReqLevel: 20, ReqMAG: 112, ReqINT: 112,
			SpriteID: 65, SoundID: 1,
			ApplyEffect: EffectMagicProtection, EffectLevel: 3,
		}
	}

	if SpellDB[66] == nil {
		SpellDB[66] = &SpellDef{
			ID: 66, Name: "Armor Break",
			Type: SpellTypeDebuff, Element: ElementEarth,
			ManaCost: 90, CastTime: 1100, Cooldown: 8000, Range: 1,
			Duration: 30,
			ReqLevel: 20, ReqMAG: 97, ReqINT: 97,
			SpriteID: 66, SoundID: 7,
		}
	}

	if SpellDB[67] == nil {
		SpellDB[67] = &SpellDef{
			ID: 67, Name: "Scan",
			Type: SpellTypeBuff, Element: ElementEarth,
			ManaCost: 50, CastTime: 900, Cooldown: 10000, Range: 0,
			Duration: 60,
			ReqLevel: 15, ReqMAG: 70, ReqINT: 70,
			SpriteID: 67, SoundID: 7,
		}
	}

	if SpellDB[68] == nil {
		SpellDB[68] = &SpellDef{
			ID: 68, Name: "Mass Heal",
			Type: SpellTypeHeal, Element: ElementNone,
			ManaCost: 120, CastTime: 1300, Cooldown: 3000, Range: 0,
			HealAmount: 136,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 68, SoundID: 45,
		}
	}

	if SpellDB[70] == nil {
		SpellDB[70] = &SpellDef{
			ID: 70, Name: "Bloody Shock Wave",
			Type: SpellTypeAOE, Element: ElementFire,
			ManaCost: 120, CastTime: 1300, Cooldown: 4000, Range: 2,
			Radius: 2,
			MinDamage: 38, MaxDamage: 94,
			ReqLevel: 20, ReqMAG: 105, ReqINT: 105,
			SpriteID: 70, SoundID: 4,
		}
	}

	if SpellDB[71] == nil {
		SpellDB[71] = &SpellDef{
			ID: 71, Name: "Mass Confusion",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 125, CastTime: 1300, Cooldown: 8000, Range: 3,
			Duration: 90,
			ReqLevel: 25, ReqMAG: 130, ReqINT: 130,
			SpriteID: 71, SoundID: 1,
			ApplyEffect: EffectConfusion, EffectLevel: 2,
		}
	}

	if SpellDB[72] == nil {
		SpellDB[72] = &SpellDef{
			ID: 72, Name: "Mass Ice Strike",
			Type: SpellTypeAOE, Element: ElementIce,
			ManaCost: 120, CastTime: 1300, Cooldown: 4000, Range: 3,
			Radius: 3,
			MinDamage: 29, MaxDamage: 71,
			ReqLevel: 25, ReqMAG: 133, ReqINT: 133,
			SpriteID: 72, SoundID: 46,
		}
	}

	if SpellDB[73] == nil {
		SpellDB[73] = &SpellDef{
			ID: 73, Name: "Cloud Kill",
			Type: SpellTypeAOE, Element: ElementEarth,
			ManaCost: 130, CastTime: 1300, Cooldown: 4000, Range: 1,
			Radius: 1,
			MinDamage: 13, MaxDamage: 23,
			Duration: 30,
			ReqLevel: 20, ReqMAG: 120, ReqINT: 120,
			SpriteID: 73, SoundID: 7,
		}
	}

	if SpellDB[74] == nil {
		SpellDB[74] = &SpellDef{
			ID: 74, Name: "Lightning Strike",
			Type: SpellTypeAOE, Element: ElementLight,
			ManaCost: 90, CastTime: 1100, Cooldown: 4000, Range: 2,
			Radius: 2,
			MinDamage: 29, MaxDamage: 71,
			ReqLevel: 25, ReqMAG: 123, ReqINT: 123,
			SpriteID: 74, SoundID: 5,
		}
	}

	if SpellDB[75] == nil {
		SpellDB[75] = &SpellDef{
			ID: 75, Name: "Trance",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 90, CastTime: 1100, Cooldown: 10000, Range: 0,
			Duration: 90,
			BuffStat: 1, BuffAmount: 12,
			ReqLevel: 20, ReqMAG: 90, ReqINT: 90,
			SpriteID: 75, SoundID: 1,
			ApplyEffect: EffectBerserk, EffectLevel: 2,
		}
	}

	if SpellDB[76] == nil {
		SpellDB[76] = &SpellDef{
			ID: 76, Name: "Cancellation",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 120, CastTime: 1300, Cooldown: 8000, Range: 1,
			Duration: 3,
			ReqLevel: 25, ReqMAG: 135, ReqINT: 135,
			SpriteID: 76, SoundID: 1,
		}
	}

	if SpellDB[77] == nil {
		SpellDB[77] = &SpellDef{
			ID: 77, Name: "Illusion Movement",
			Type: SpellTypeDebuff, Element: ElementLight,
			ManaCost: 130, CastTime: 1300, Cooldown: 8000, Range: 2,
			Duration: 30,
			ReqLevel: 25, ReqMAG: 160, ReqINT: 160,
			SpriteID: 77, SoundID: 5,
			ApplyEffect: EffectConfusion, EffectLevel: 4,
		}
	}

	if SpellDB[78] == nil {
		SpellDB[78] = &SpellDef{
			ID: 78, Name: "Divine Revenge",
			Type: SpellTypeDamage, Element: ElementFire,
			ManaCost: 80, CastTime: 1100, Cooldown: 2000, Range: 2,
			MinDamage: 43, MaxDamage: 109,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 78, SoundID: 4,
		}
	}

	if SpellDB[80] == nil {
		SpellDB[80] = &SpellDef{
			ID: 80, Name: "Illusion",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 143, CastTime: 1300, Cooldown: 8000, Range: 2,
			Duration: 30,
			ReqLevel: 25, ReqMAG: 150, ReqINT: 150,
			SpriteID: 80, SoundID: 1,
			ApplyEffect: EffectConfusion, EffectLevel: 3,
		}
	}

	if SpellDB[81] == nil {
		SpellDB[81] = &SpellDef{
			ID: 81, Name: "Meteor Strike",
			Type: SpellTypeDamage, Element: ElementFire,
			ManaCost: 120, CastTime: 1300, Cooldown: 2000, Range: 2,
			MinDamage: 47, MaxDamage: 124,
			ReqLevel: 30, ReqMAG: 169, ReqINT: 169,
			SpriteID: 81, SoundID: 4,
		}
	}

	if SpellDB[82] == nil {
		SpellDB[82] = &SpellDef{
			ID: 82, Name: "Warrior Spirit",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 500, CastTime: 1500, Cooldown: 180000, Range: 0,
			Duration: 60,
			ReqLevel: 25, ReqMAG: 156, ReqINT: 156,
			SpriteID: 82, SoundID: 1,
		}
	}

	if SpellDB[83] == nil {
		SpellDB[83] = &SpellDef{
			ID: 83, Name: "Inhibition Casting",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 180, CastTime: 1500, Cooldown: 8000, Range: 1,
			Duration: 40,
			ReqLevel: 30, ReqMAG: 180, ReqINT: 180,
			SpriteID: 83, SoundID: 1,
			ApplyEffect: EffectInhibition, EffectLevel: 1,
		}
	}

	if SpellDB[84] == nil {
		SpellDB[84] = &SpellDef{
			ID: 84, Name: "Magic Drain",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 200, CastTime: 1500, Cooldown: 8000, Range: 1,
			Duration: 30,
			ReqLevel: 30, ReqMAG: 166, ReqINT: 166,
			SpriteID: 84, SoundID: 1,
		}
	}

	if SpellDB[85] == nil {
		SpellDB[85] = &SpellDef{
			ID: 85, Name: "Blizzard",
			Type: SpellTypeAOE, Element: ElementIce,
			ManaCost: 170, CastTime: 1500, Cooldown: 4000, Range: 2,
			Radius: 2,
			MinDamage: 44, MaxDamage: 98,
			Duration: 20,
			ReqLevel: 30, ReqMAG: 195, ReqINT: 195,
			SpriteID: 85, SoundID: 46,
		}
	}

	if SpellDB[86] == nil {
		SpellDB[86] = &SpellDef{
			ID: 86, Name: "Regenerate",
			Type: SpellTypeHeal, Element: ElementNone,
			ManaCost: 220, CastTime: 1500, Cooldown: 3000, Range: 0,
			HealAmount: 909,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 86, SoundID: 45,
		}
	}

	if SpellDB[87] == nil {
		SpellDB[87] = &SpellDef{
			ID: 87, Name: "Magic Mantle",
			Type: SpellTypeBuff, Element: ElementNone,
			ManaCost: 88, CastTime: 1100, Cooldown: 180000, Range: 0,
			Duration: 45,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 87, SoundID: 1,
			ApplyEffect: EffectDefenseShield, EffectLevel: 3,
		}
	}

	if SpellDB[88] == nil {
		SpellDB[88] = &SpellDef{
			ID: 88, Name: "Entangle",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 120, CastTime: 1300, Cooldown: 8000, Range: 1,
			Duration: 75,
			BuffStat: 3, BuffAmount: -45,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 88, SoundID: 1,
			ApplyEffect: EffectIce, EffectLevel: 9,
		}
	}

	if SpellDB[90] == nil {
		SpellDB[90] = &SpellDef{
			ID: 90, Name: "Mass Illusion",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 200, CastTime: 1500, Cooldown: 8000, Range: 3,
			Duration: 60,
			ReqLevel: 30, ReqMAG: 180, ReqINT: 180,
			SpriteID: 90, SoundID: 1,
			ApplyEffect: EffectConfusion, EffectLevel: 3,
		}
	}

	if SpellDB[91] == nil {
		SpellDB[91] = &SpellDef{
			ID: 91, Name: "Mass Blizzard",
			Type: SpellTypeAOE, Element: ElementIce,
			ManaCost: 319, CastTime: 1500, Cooldown: 4000, Range: 3,
			Radius: 3,
			MinDamage: 56, MaxDamage: 182,
			ReqLevel: 35, ReqMAG: 250, ReqINT: 250,
			SpriteID: 91, SoundID: 46,
		}
	}

	if SpellDB[92] == nil {
		SpellDB[92] = &SpellDef{
			ID: 92, Name: "Mass Armor Break",
			Type: SpellTypeDebuff, Element: ElementEarth,
			ManaCost: 145, CastTime: 1300, Cooldown: 8000, Range: 3,
			Duration: 30,
			ReqLevel: 35, ReqMAG: 208, ReqINT: 208,
			SpriteID: 92, SoundID: 7,
		}
	}

	if SpellDB[93] == nil {
		SpellDB[93] = &SpellDef{
			ID: 93, Name: "Mass Lightning Strike",
			Type: SpellTypeAOE, Element: ElementLight,
			ManaCost: 254, CastTime: 1500, Cooldown: 4000, Range: 3,
			Radius: 3,
			MinDamage: 50, MaxDamage: 120,
			ReqLevel: 35, ReqMAG: 231, ReqINT: 231,
			SpriteID: 93, SoundID: 5,
		}
	}

	if SpellDB[94] == nil {
		SpellDB[94] = &SpellDef{
			ID: 94, Name: "Resurrection",
			Type: SpellTypeHeal, Element: ElementNone,
			ManaCost: 200, CastTime: 1500, Cooldown: 600000, Range: 2,
			HealAmount: 3,
			ReqLevel: 1, ReqMAG: 10, ReqINT: 10,
			SpriteID: 94, SoundID: 45,
		}
	}

	if SpellDB[95] == nil {
		SpellDB[95] = &SpellDef{
			ID: 95, Name: "Mass Illusion Movement",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 220, CastTime: 1500, Cooldown: 8000, Range: 3,
			Duration: 60,
			ReqLevel: 30, ReqMAG: 200, ReqINT: 200,
			SpriteID: 95, SoundID: 1,
			ApplyEffect: EffectConfusion, EffectLevel: 4,
		}
	}

	if SpellDB[96] == nil {
		SpellDB[96] = &SpellDef{
			ID: 96, Name: "Earth Shock Wave",
			Type: SpellTypeAOE, Element: ElementEarth,
			ManaCost: 220, CastTime: 1500, Cooldown: 4000, Range: 2,
			Radius: 2,
			MinDamage: 105, MaxDamage: 293,
			ReqLevel: 35, ReqMAG: 215, ReqINT: 215,
			SpriteID: 96, SoundID: 7,
		}
	}

	if SpellDB[97] == nil {
		SpellDB[97] = &SpellDef{
			ID: 97, Name: "Explosion",
			Type: SpellTypeAOE, Element: ElementNone,
			ManaCost: 150, CastTime: 1300, Cooldown: 4000, Range: 4,
			Radius: 4,
			MinDamage: 24, MaxDamage: 59,
			ReqLevel: 30, ReqMAG: 182, ReqINT: 182,
			SpriteID: 97, SoundID: 1,
		}
	}

	if SpellDB[98] == nil {
		SpellDB[98] = &SpellDef{
			ID: 98, Name: "Medusa Kiss",
			Type: SpellTypeDebuff, Element: ElementNone,
			ManaCost: 120, CastTime: 1300, Cooldown: 8000, Range: 1,
			Duration: 180,
			BuffStat: 3, BuffAmount: -100,
			ReqLevel: 35, ReqMAG: 235, ReqINT: 235,
			SpriteID: 98, SoundID: 1,
			ApplyEffect: EffectIce, EffectLevel: 20,
		}
	}

}
