// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client -> Server: Login or register
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`  // 3-20 chars, alphanumeric
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`  // 6-30 chars
	Register      bool                   `protobuf:"varint,3,opt,name=register,proto3" json:"register,omitempty"` // true = create new account
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetRegister() bool {
	if x != nil {
		return x.Register
	}
	return false
}

// Server -> Client: Login/register result
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Characters    []*CharacterSummary    `protobuf:"bytes,3,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LoginResponse) GetCharacters() []*CharacterSummary {
	if x != nil {
		return x.Characters
	}
	return nil
}

// Summary of a character shown on character select screen
type CharacterSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Side          int32                  `protobuf:"varint,5,opt,name=side,proto3" json:"side,omitempty"` // 0=neutral, 1=aresden, 2=elvine
	MapName       string                 `protobuf:"bytes,6,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	Appearance    *Appearance            `protobuf:"bytes,7,opt,name=appearance,proto3" json:"appearance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterSummary) Reset() {
	*x = CharacterSummary{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSummary) ProtoMessage() {}

func (x *CharacterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSummary.ProtoReflect.Descriptor instead.
func (*CharacterSummary) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterSummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharacterSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterSummary) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharacterSummary) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CharacterSummary) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *CharacterSummary) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *CharacterSummary) GetAppearance() *Appearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

// Client -> Server: Create a new character
type CreateCharacterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                            // 3-10 chars
	Gender         int32                  `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`                                       // 0=male, 1=female
	SkinColor      int32                  `protobuf:"varint,3,opt,name=skin_color,json=skinColor,proto3" json:"skin_color,omitempty"`                // 0-2
	HairStyle      int32                  `protobuf:"varint,4,opt,name=hair_style,json=hairStyle,proto3" json:"hair_style,omitempty"`                // 0-12
	HairColor      int32                  `protobuf:"varint,5,opt,name=hair_color,json=hairColor,proto3" json:"hair_color,omitempty"`                // 0-7
	UnderwearColor int32                  `protobuf:"varint,6,opt,name=underwear_color,json=underwearColor,proto3" json:"underwear_color,omitempty"` // 0-7
	Str            int32                  `protobuf:"varint,7,opt,name=str,proto3" json:"str,omitempty"`                                             // each >= 10, total = 70
	Vit            int32                  `protobuf:"varint,8,opt,name=vit,proto3" json:"vit,omitempty"`
	Dex            int32                  `protobuf:"varint,9,opt,name=dex,proto3" json:"dex,omitempty"`
	IntStat        int32                  `protobuf:"varint,10,opt,name=int_stat,json=intStat,proto3" json:"int_stat,omitempty"`
	Mag            int32                  `protobuf:"varint,11,opt,name=mag,proto3" json:"mag,omitempty"`
	Charisma       int32                  `protobuf:"varint,12,opt,name=charisma,proto3" json:"charisma,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCharacterRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateCharacterRequest) GetSkinColor() int32 {
	if x != nil {
		return x.SkinColor
	}
	return 0
}

func (x *CreateCharacterRequest) GetHairStyle() int32 {
	if x != nil {
		return x.HairStyle
	}
	return 0
}

func (x *CreateCharacterRequest) GetHairColor() int32 {
	if x != nil {
		return x.HairColor
	}
	return 0
}

func (x *CreateCharacterRequest) GetUnderwearColor() int32 {
	if x != nil {
		return x.UnderwearColor
	}
	return 0
}

func (x *CreateCharacterRequest) GetStr() int32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *CreateCharacterRequest) GetVit() int32 {
	if x != nil {
		return x.Vit
	}
	return 0
}

func (x *CreateCharacterRequest) GetDex() int32 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *CreateCharacterRequest) GetIntStat() int32 {
	if x != nil {
		return x.IntStat
	}
	return 0
}

func (x *CreateCharacterRequest) GetMag() int32 {
	if x != nil {
		return x.Mag
	}
	return 0
}

func (x *CreateCharacterRequest) GetCharisma() int32 {
	if x != nil {
		return x.Charisma
	}
	return 0
}

// Server -> Client: Character creation result
type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Characters    []*CharacterSummary    `protobuf:"bytes,3,rep,name=characters,proto3" json:"characters,omitempty"` // updated list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCharacterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateCharacterResponse) GetCharacters() []*CharacterSummary {
	if x != nil {
		return x.Characters
	}
	return nil
}

// Client -> Server: Enter game with a character
type EnterGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterGameRequest) Reset() {
	*x = EnterGameRequest{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameRequest) ProtoMessage() {}

func (x *EnterGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameRequest.ProtoReflect.Descriptor instead.
func (*EnterGameRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *EnterGameRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

// Client -> Server: Delete a character
type DeleteCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterRequest) Reset() {
	*x = DeleteCharacterRequest{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterRequest) ProtoMessage() {}

func (x *DeleteCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterRequest.ProtoReflect.Descriptor instead.
func (*DeleteCharacterRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCharacterRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type DeleteCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Characters    []*CharacterSummary    `protobuf:"bytes,3,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResponse) Reset() {
	*x = DeleteCharacterResponse{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResponse) ProtoMessage() {}

func (x *DeleteCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCharacterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteCharacterResponse) GetCharacters() []*CharacterSummary {
	if x != nil {
		return x.Characters
	}
	return nil
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\bhbonline\x1a\fcommon.proto\"b\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bregister\x18\x03 \x01(\bR\bregister\"{\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12:\n" +
	"\n" +
	"characters\x18\x03 \x03(\v2\x1a.hbonline.CharacterSummaryR\n" +
	"characters\"\xc9\x01\n" +
	"\x10CharacterSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x12\n" +
	"\x04side\x18\x05 \x01(\x05R\x04side\x12\x19\n" +
	"\bmap_name\x18\x06 \x01(\tR\amapName\x124\n" +
	"\n" +
	"appearance\x18\a \x01(\v2\x14.hbonline.AppearanceR\n" +
	"appearance\"\xc9\x02\n" +
	"\x16CreateCharacterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\x05R\x06gender\x12\x1d\n" +
	"\n" +
	"skin_color\x18\x03 \x01(\x05R\tskinColor\x12\x1d\n" +
	"\n" +
	"hair_style\x18\x04 \x01(\x05R\thairStyle\x12\x1d\n" +
	"\n" +
	"hair_color\x18\x05 \x01(\x05R\thairColor\x12'\n" +
	"\x0funderwear_color\x18\x06 \x01(\x05R\x0eunderwearColor\x12\x10\n" +
	"\x03str\x18\a \x01(\x05R\x03str\x12\x10\n" +
	"\x03vit\x18\b \x01(\x05R\x03vit\x12\x10\n" +
	"\x03dex\x18\t \x01(\x05R\x03dex\x12\x19\n" +
	"\bint_stat\x18\n" +
	" \x01(\x05R\aintStat\x12\x10\n" +
	"\x03mag\x18\v \x01(\x05R\x03mag\x12\x1a\n" +
	"\bcharisma\x18\f \x01(\x05R\bcharisma\"\x85\x01\n" +
	"\x17CreateCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12:\n" +
	"\n" +
	"characters\x18\x03 \x03(\v2\x1a.hbonline.CharacterSummaryR\n" +
	"characters\"5\n" +
	"\x10EnterGameRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\";\n" +
	"\x16DeleteCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\"\x85\x01\n" +
	"\x17DeleteCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12:\n" +
	"\n" +
	"characters\x18\x03 \x03(\v2\x1a.hbonline.CharacterSummaryR\n" +
	"charactersB0Z.github.com/juanrossi/hbonline/server/pkg/protob\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),            // 0: hbonline.LoginRequest
	(*LoginResponse)(nil),           // 1: hbonline.LoginResponse
	(*CharacterSummary)(nil),        // 2: hbonline.CharacterSummary
	(*CreateCharacterRequest)(nil),  // 3: hbonline.CreateCharacterRequest
	(*CreateCharacterResponse)(nil), // 4: hbonline.CreateCharacterResponse
	(*EnterGameRequest)(nil),        // 5: hbonline.EnterGameRequest
	(*DeleteCharacterRequest)(nil),  // 6: hbonline.DeleteCharacterRequest
	(*DeleteCharacterResponse)(nil), // 7: hbonline.DeleteCharacterResponse
	(*Appearance)(nil),              // 8: hbonline.Appearance
}
var file_auth_proto_depIdxs = []int32{
	2, // 0: hbonline.LoginResponse.characters:type_name -> hbonline.CharacterSummary
	8, // 1: hbonline.CharacterSummary.appearance:type_name -> hbonline.Appearance
	2, // 2: hbonline.CreateCharacterResponse.characters:type_name -> hbonline.CharacterSummary
	2, // 3: hbonline.DeleteCharacterResponse.characters:type_name -> hbonline.CharacterSummary
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
