// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Appearance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Gender         int32                  `protobuf:"varint,1,opt,name=gender,proto3" json:"gender,omitempty"`                                       // 0=male, 1=female
	SkinColor      int32                  `protobuf:"varint,2,opt,name=skin_color,json=skinColor,proto3" json:"skin_color,omitempty"`                // 0-2
	HairStyle      int32                  `protobuf:"varint,3,opt,name=hair_style,json=hairStyle,proto3" json:"hair_style,omitempty"`                // 0-12
	HairColor      int32                  `protobuf:"varint,4,opt,name=hair_color,json=hairColor,proto3" json:"hair_color,omitempty"`                // 0-7
	UnderwearColor int32                  `protobuf:"varint,5,opt,name=underwear_color,json=underwearColor,proto3" json:"underwear_color,omitempty"` // 0-7
	BodyArmor      int32                  `protobuf:"varint,6,opt,name=body_armor,json=bodyArmor,proto3" json:"body_armor,omitempty"`                // equipment sprite index (0=none)
	ArmArmor       int32                  `protobuf:"varint,7,opt,name=arm_armor,json=armArmor,proto3" json:"arm_armor,omitempty"`
	Leggings       int32                  `protobuf:"varint,8,opt,name=leggings,proto3" json:"leggings,omitempty"`
	Helm           int32                  `protobuf:"varint,9,opt,name=helm,proto3" json:"helm,omitempty"`
	Weapon         int32                  `protobuf:"varint,10,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Shield         int32                  `protobuf:"varint,11,opt,name=shield,proto3" json:"shield,omitempty"`
	Cape           int32                  `protobuf:"varint,12,opt,name=cape,proto3" json:"cape,omitempty"`
	Boots          int32                  `protobuf:"varint,13,opt,name=boots,proto3" json:"boots,omitempty"`
	ApprColor      int32                  `protobuf:"varint,14,opt,name=appr_color,json=apprColor,proto3" json:"appr_color,omitempty"` // dye color
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Appearance) Reset() {
	*x = Appearance{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appearance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appearance) ProtoMessage() {}

func (x *Appearance) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appearance.ProtoReflect.Descriptor instead.
func (*Appearance) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Appearance) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *Appearance) GetSkinColor() int32 {
	if x != nil {
		return x.SkinColor
	}
	return 0
}

func (x *Appearance) GetHairStyle() int32 {
	if x != nil {
		return x.HairStyle
	}
	return 0
}

func (x *Appearance) GetHairColor() int32 {
	if x != nil {
		return x.HairColor
	}
	return 0
}

func (x *Appearance) GetUnderwearColor() int32 {
	if x != nil {
		return x.UnderwearColor
	}
	return 0
}

func (x *Appearance) GetBodyArmor() int32 {
	if x != nil {
		return x.BodyArmor
	}
	return 0
}

func (x *Appearance) GetArmArmor() int32 {
	if x != nil {
		return x.ArmArmor
	}
	return 0
}

func (x *Appearance) GetLeggings() int32 {
	if x != nil {
		return x.Leggings
	}
	return 0
}

func (x *Appearance) GetHelm() int32 {
	if x != nil {
		return x.Helm
	}
	return 0
}

func (x *Appearance) GetWeapon() int32 {
	if x != nil {
		return x.Weapon
	}
	return 0
}

func (x *Appearance) GetShield() int32 {
	if x != nil {
		return x.Shield
	}
	return 0
}

func (x *Appearance) GetCape() int32 {
	if x != nil {
		return x.Cape
	}
	return 0
}

func (x *Appearance) GetBoots() int32 {
	if x != nil {
		return x.Boots
	}
	return 0
}

func (x *Appearance) GetApprColor() int32 {
	if x != nil {
		return x.ApprColor
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bhbonline\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\x8f\x03\n" +
	"\n" +
	"Appearance\x12\x16\n" +
	"\x06gender\x18\x01 \x01(\x05R\x06gender\x12\x1d\n" +
	"\n" +
	"skin_color\x18\x02 \x01(\x05R\tskinColor\x12\x1d\n" +
	"\n" +
	"hair_style\x18\x03 \x01(\x05R\thairStyle\x12\x1d\n" +
	"\n" +
	"hair_color\x18\x04 \x01(\x05R\thairColor\x12'\n" +
	"\x0funderwear_color\x18\x05 \x01(\x05R\x0eunderwearColor\x12\x1d\n" +
	"\n" +
	"body_armor\x18\x06 \x01(\x05R\tbodyArmor\x12\x1b\n" +
	"\tarm_armor\x18\a \x01(\x05R\barmArmor\x12\x1a\n" +
	"\bleggings\x18\b \x01(\x05R\bleggings\x12\x12\n" +
	"\x04helm\x18\t \x01(\x05R\x04helm\x12\x16\n" +
	"\x06weapon\x18\n" +
	" \x01(\x05R\x06weapon\x12\x16\n" +
	"\x06shield\x18\v \x01(\x05R\x06shield\x12\x12\n" +
	"\x04cape\x18\f \x01(\x05R\x04cape\x12\x14\n" +
	"\x05boots\x18\r \x01(\x05R\x05boots\x12\x1d\n" +
	"\n" +
	"appr_color\x18\x0e \x01(\x05R\tapprColorB0Z.github.com/juanrossi/hbonline/server/pkg/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(*Vec2)(nil),       // 0: hbonline.Vec2
	(*Appearance)(nil), // 1: hbonline.Appearance
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
