// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server -> Client: Full game state on entering
type EnterGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerContents        `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	MapInfo       *MapInfo               `protobuf:"bytes,2,opt,name=map_info,json=mapInfo,proto3" json:"map_info,omitempty"`
	NearbyPlayers []*EntityInfo          `protobuf:"bytes,3,rep,name=nearby_players,json=nearbyPlayers,proto3" json:"nearby_players,omitempty"`
	NearbyNpcs    []*EntityInfo          `protobuf:"bytes,4,rep,name=nearby_npcs,json=nearbyNpcs,proto3" json:"nearby_npcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterGameResponse) Reset() {
	*x = EnterGameResponse{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameResponse) ProtoMessage() {}

func (x *EnterGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameResponse.ProtoReflect.Descriptor instead.
func (*EnterGameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *EnterGameResponse) GetPlayer() *PlayerContents {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *EnterGameResponse) GetMapInfo() *MapInfo {
	if x != nil {
		return x.MapInfo
	}
	return nil
}

func (x *EnterGameResponse) GetNearbyPlayers() []*EntityInfo {
	if x != nil {
		return x.NearbyPlayers
	}
	return nil
}

func (x *EnterGameResponse) GetNearbyNpcs() []*EntityInfo {
	if x != nil {
		return x.NearbyNpcs
	}
	return nil
}

// Full player data sent to the owning client
type PlayerContents struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ObjectId   int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MapName    string                 `protobuf:"bytes,3,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	Position   *Vec2                  `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Direction  int32                  `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Appearance *Appearance            `protobuf:"bytes,6,opt,name=appearance,proto3" json:"appearance,omitempty"`
	// Stats
	Level         int32 `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Experience    int64 `protobuf:"varint,8,opt,name=experience,proto3" json:"experience,omitempty"`
	Hp            int32 `protobuf:"varint,9,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32 `protobuf:"varint,10,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Mp            int32 `protobuf:"varint,11,opt,name=mp,proto3" json:"mp,omitempty"`
	MaxMp         int32 `protobuf:"varint,12,opt,name=max_mp,json=maxMp,proto3" json:"max_mp,omitempty"`
	Sp            int32 `protobuf:"varint,13,opt,name=sp,proto3" json:"sp,omitempty"`
	MaxSp         int32 `protobuf:"varint,14,opt,name=max_sp,json=maxSp,proto3" json:"max_sp,omitempty"`
	Str           int32 `protobuf:"varint,15,opt,name=str,proto3" json:"str,omitempty"`
	Vit           int32 `protobuf:"varint,16,opt,name=vit,proto3" json:"vit,omitempty"`
	Dex           int32 `protobuf:"varint,17,opt,name=dex,proto3" json:"dex,omitempty"`
	IntStat       int32 `protobuf:"varint,18,opt,name=int_stat,json=intStat,proto3" json:"int_stat,omitempty"`
	Mag           int32 `protobuf:"varint,19,opt,name=mag,proto3" json:"mag,omitempty"`
	Charisma      int32 `protobuf:"varint,20,opt,name=charisma,proto3" json:"charisma,omitempty"`
	LuPool        int32 `protobuf:"varint,21,opt,name=lu_pool,json=luPool,proto3" json:"lu_pool,omitempty"`
	Side          int32 `protobuf:"varint,22,opt,name=side,proto3" json:"side,omitempty"` // 0=neutral, 1=aresden, 2=elvine
	Gold          int64 `protobuf:"varint,23,opt,name=gold,proto3" json:"gold,omitempty"`
	PkCount       int32 `protobuf:"varint,24,opt,name=pk_count,json=pkCount,proto3" json:"pk_count,omitempty"`
	EkCount       int32 `protobuf:"varint,25,opt,name=ek_count,json=ekCount,proto3" json:"ek_count,omitempty"`
	Hunger        int32 `protobuf:"varint,26,opt,name=hunger,proto3" json:"hunger,omitempty"`
	AdminLevel    int32 `protobuf:"varint,27,opt,name=admin_level,json=adminLevel,proto3" json:"admin_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerContents) Reset() {
	*x = PlayerContents{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerContents) ProtoMessage() {}

func (x *PlayerContents) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerContents.ProtoReflect.Descriptor instead.
func (*PlayerContents) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerContents) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *PlayerContents) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerContents) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *PlayerContents) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerContents) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *PlayerContents) GetAppearance() *Appearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

func (x *PlayerContents) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerContents) GetExperience() int64 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *PlayerContents) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerContents) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PlayerContents) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *PlayerContents) GetMaxMp() int32 {
	if x != nil {
		return x.MaxMp
	}
	return 0
}

func (x *PlayerContents) GetSp() int32 {
	if x != nil {
		return x.Sp
	}
	return 0
}

func (x *PlayerContents) GetMaxSp() int32 {
	if x != nil {
		return x.MaxSp
	}
	return 0
}

func (x *PlayerContents) GetStr() int32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *PlayerContents) GetVit() int32 {
	if x != nil {
		return x.Vit
	}
	return 0
}

func (x *PlayerContents) GetDex() int32 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *PlayerContents) GetIntStat() int32 {
	if x != nil {
		return x.IntStat
	}
	return 0
}

func (x *PlayerContents) GetMag() int32 {
	if x != nil {
		return x.Mag
	}
	return 0
}

func (x *PlayerContents) GetCharisma() int32 {
	if x != nil {
		return x.Charisma
	}
	return 0
}

func (x *PlayerContents) GetLuPool() int32 {
	if x != nil {
		return x.LuPool
	}
	return 0
}

func (x *PlayerContents) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *PlayerContents) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlayerContents) GetPkCount() int32 {
	if x != nil {
		return x.PkCount
	}
	return 0
}

func (x *PlayerContents) GetEkCount() int32 {
	if x != nil {
		return x.EkCount
	}
	return 0
}

func (x *PlayerContents) GetHunger() int32 {
	if x != nil {
		return x.Hunger
	}
	return 0
}

func (x *PlayerContents) GetAdminLevel() int32 {
	if x != nil {
		return x.AdminLevel
	}
	return 0
}

// Map metadata sent to client
type MapInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	CollisionGrid []byte                 `protobuf:"bytes,4,opt,name=collision_grid,json=collisionGrid,proto3" json:"collision_grid,omitempty"` // packed bitfield: 1=blocked, row-major
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInfo) Reset() {
	*x = MapInfo{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInfo) ProtoMessage() {}

func (x *MapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInfo.ProtoReflect.Descriptor instead.
func (*MapInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *MapInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapInfo) GetCollisionGrid() []byte {
	if x != nil {
		return x.CollisionGrid
	}
	return nil
}

// Client -> Server: Movement/action request
type MotionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     int32                  `protobuf:"varint,1,opt,name=direction,proto3" json:"direction,omitempty"`               // 1=N, 2=NE, 3=E, 4=SE, 5=S, 6=SW, 7=W, 8=NW
	Action        int32                  `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`                     // 0=stop, 1=walk, 2=run, 3=attack, 4=magic, 5=getitem
	Position      *Vec2                  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`                  // client-reported tile position
	TargetId      int32                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // target object ID (for attack/magic)
	SpellId       int32                  `protobuf:"varint,5,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`    // spell ID (for magic action)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotionRequest) Reset() {
	*x = MotionRequest{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotionRequest) ProtoMessage() {}

func (x *MotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotionRequest.ProtoReflect.Descriptor instead.
func (*MotionRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *MotionRequest) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *MotionRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *MotionRequest) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MotionRequest) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *MotionRequest) GetSpellId() int32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

// Server -> Client: Entity moved/acted (broadcast)
type MotionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	OwnerType     int32                  `protobuf:"varint,2,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"` // 1=player, 2=npc
	Action        int32                  `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	Direction     int32                  `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Destination   *Vec2                  `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Speed         int32                  `protobuf:"varint,7,opt,name=speed,proto3" json:"speed,omitempty"` // ms per tile
	Appearance    *Appearance            `protobuf:"bytes,8,opt,name=appearance,proto3" json:"appearance,omitempty"`
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"` // 0=alive, 1=dead, 2=invisible
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotionEvent) Reset() {
	*x = MotionEvent{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotionEvent) ProtoMessage() {}

func (x *MotionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotionEvent.ProtoReflect.Descriptor instead.
func (*MotionEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *MotionEvent) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *MotionEvent) GetOwnerType() int32 {
	if x != nil {
		return x.OwnerType
	}
	return 0
}

func (x *MotionEvent) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *MotionEvent) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *MotionEvent) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MotionEvent) GetDestination() *Vec2 {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *MotionEvent) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *MotionEvent) GetAppearance() *Appearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

func (x *MotionEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MotionEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// Server -> Client: A player appeared in range
type PlayerAppear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Direction     int32                  `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Appearance    *Appearance            `protobuf:"bytes,5,opt,name=appearance,proto3" json:"appearance,omitempty"`
	Action        int32                  `protobuf:"varint,6,opt,name=action,proto3" json:"action,omitempty"`
	Level         int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Side          int32                  `protobuf:"varint,8,opt,name=side,proto3" json:"side,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	PkCount       int32                  `protobuf:"varint,10,opt,name=pk_count,json=pkCount,proto3" json:"pk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAppear) Reset() {
	*x = PlayerAppear{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAppear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAppear) ProtoMessage() {}

func (x *PlayerAppear) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAppear.ProtoReflect.Descriptor instead.
func (*PlayerAppear) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerAppear) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *PlayerAppear) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerAppear) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerAppear) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *PlayerAppear) GetAppearance() *Appearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

func (x *PlayerAppear) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *PlayerAppear) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerAppear) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *PlayerAppear) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PlayerAppear) GetPkCount() int32 {
	if x != nil {
		return x.PkCount
	}
	return 0
}

// Server -> Client: A player left range
type PlayerDisappear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDisappear) Reset() {
	*x = PlayerDisappear{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDisappear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisappear) ProtoMessage() {}

func (x *PlayerDisappear) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisappear.ProtoReflect.Descriptor instead.
func (*PlayerDisappear) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerDisappear) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

// Server -> Client: An NPC appeared in range
type NpcAppear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NpcType       int32                  `protobuf:"varint,3,opt,name=npc_type,json=npcType,proto3" json:"npc_type,omitempty"` // monster/NPC type ID
	Position      *Vec2                  `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Direction     int32                  `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Action        int32                  `protobuf:"varint,6,opt,name=action,proto3" json:"action,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcAppear) Reset() {
	*x = NpcAppear{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcAppear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcAppear) ProtoMessage() {}

func (x *NpcAppear) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcAppear.ProtoReflect.Descriptor instead.
func (*NpcAppear) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *NpcAppear) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *NpcAppear) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NpcAppear) GetNpcType() int32 {
	if x != nil {
		return x.NpcType
	}
	return 0
}

func (x *NpcAppear) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *NpcAppear) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *NpcAppear) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *NpcAppear) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// Server -> Client: An NPC left range
type NpcDisappear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcDisappear) Reset() {
	*x = NpcDisappear{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcDisappear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcDisappear) ProtoMessage() {}

func (x *NpcDisappear) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcDisappear.ProtoReflect.Descriptor instead.
func (*NpcDisappear) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *NpcDisappear) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

// Server -> Client: NPC moved/acted
type NpcMotion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Action        int32                  `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	Direction     int32                  `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Destination   *Vec2                  `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	Speed         int32                  `protobuf:"varint,6,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcMotion) Reset() {
	*x = NpcMotion{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcMotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcMotion) ProtoMessage() {}

func (x *NpcMotion) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcMotion.ProtoReflect.Descriptor instead.
func (*NpcMotion) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *NpcMotion) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *NpcMotion) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *NpcMotion) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *NpcMotion) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *NpcMotion) GetDestination() *Vec2 {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *NpcMotion) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

// Server -> Client: Generic notification
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 0=info, 1=warning, 2=error, 3=system
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// Server -> Client: Map change (teleport)
type MapChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapName       string                 `protobuf:"bytes,1,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Direction     int32                  `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChangeResponse) Reset() {
	*x = MapChangeResponse{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChangeResponse) ProtoMessage() {}

func (x *MapChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChangeResponse.ProtoReflect.Descriptor instead.
func (*MapChangeResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *MapChangeResponse) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *MapChangeResponse) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MapChangeResponse) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

// Entity info for initial world state
type EntityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	EntityType    int32                  `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // 1=player, 2=npc
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Direction     int32                  `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Action        int32                  `protobuf:"varint,6,opt,name=action,proto3" json:"action,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Appearance    *Appearance            `protobuf:"bytes,8,opt,name=appearance,proto3" json:"appearance,omitempty"`           // only for players
	NpcType       int32                  `protobuf:"varint,9,opt,name=npc_type,json=npcType,proto3" json:"npc_type,omitempty"` // only for NPCs
	Level         int32                  `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
	Side          int32                  `protobuf:"varint,11,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityInfo) Reset() {
	*x = EntityInfo{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfo) ProtoMessage() {}

func (x *EntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfo.ProtoReflect.Descriptor instead.
func (*EntityInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *EntityInfo) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *EntityInfo) GetEntityType() int32 {
	if x != nil {
		return x.EntityType
	}
	return 0
}

func (x *EntityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityInfo) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityInfo) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *EntityInfo) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *EntityInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EntityInfo) GetAppearance() *Appearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

func (x *EntityInfo) GetNpcType() int32 {
	if x != nil {
		return x.NpcType
	}
	return 0
}

func (x *EntityInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EntityInfo) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\bhbonline\x1a\fcommon.proto\"\xe7\x01\n" +
	"\x11EnterGameResponse\x120\n" +
	"\x06player\x18\x01 \x01(\v2\x18.hbonline.PlayerContentsR\x06player\x12,\n" +
	"\bmap_info\x18\x02 \x01(\v2\x11.hbonline.MapInfoR\amapInfo\x12;\n" +
	"\x0enearby_players\x18\x03 \x03(\v2\x14.hbonline.EntityInfoR\rnearbyPlayers\x125\n" +
	"\vnearby_npcs\x18\x04 \x03(\v2\x14.hbonline.EntityInfoR\n" +
	"nearbyNpcs\"\xb6\x05\n" +
	"\x0ePlayerContents\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bmap_name\x18\x03 \x01(\tR\amapName\x12*\n" +
	"\bposition\x18\x04 \x01(\v2\x0e.hbonline.Vec2R\bposition\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x05R\tdirection\x124\n" +
	"\n" +
	"appearance\x18\x06 \x01(\v2\x14.hbonline.AppearanceR\n" +
	"appearance\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\b \x01(\x03R\n" +
	"experience\x12\x0e\n" +
	"\x02hp\x18\t \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\n" +
	" \x01(\x05R\x05maxHp\x12\x0e\n" +
	"\x02mp\x18\v \x01(\x05R\x02mp\x12\x15\n" +
	"\x06max_mp\x18\f \x01(\x05R\x05maxMp\x12\x0e\n" +
	"\x02sp\x18\r \x01(\x05R\x02sp\x12\x15\n" +
	"\x06max_sp\x18\x0e \x01(\x05R\x05maxSp\x12\x10\n" +
	"\x03str\x18\x0f \x01(\x05R\x03str\x12\x10\n" +
	"\x03vit\x18\x10 \x01(\x05R\x03vit\x12\x10\n" +
	"\x03dex\x18\x11 \x01(\x05R\x03dex\x12\x19\n" +
	"\bint_stat\x18\x12 \x01(\x05R\aintStat\x12\x10\n" +
	"\x03mag\x18\x13 \x01(\x05R\x03mag\x12\x1a\n" +
	"\bcharisma\x18\x14 \x01(\x05R\bcharisma\x12\x17\n" +
	"\alu_pool\x18\x15 \x01(\x05R\x06luPool\x12\x12\n" +
	"\x04side\x18\x16 \x01(\x05R\x04side\x12\x12\n" +
	"\x04gold\x18\x17 \x01(\x03R\x04gold\x12\x19\n" +
	"\bpk_count\x18\x18 \x01(\x05R\apkCount\x12\x19\n" +
	"\bek_count\x18\x19 \x01(\x05R\aekCount\x12\x16\n" +
	"\x06hunger\x18\x1a \x01(\x05R\x06hunger\x12\x1f\n" +
	"\vadmin_level\x18\x1b \x01(\x05R\n" +
	"adminLevel\"r\n" +
	"\aMapInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12%\n" +
	"\x0ecollision_grid\x18\x04 \x01(\fR\rcollisionGrid\"\xa9\x01\n" +
	"\rMotionRequest\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\x05R\tdirection\x12\x16\n" +
	"\x06action\x18\x02 \x01(\x05R\x06action\x12*\n" +
	"\bposition\x18\x03 \x01(\v2\x0e.hbonline.Vec2R\bposition\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x05R\btargetId\x12\x19\n" +
	"\bspell_id\x18\x05 \x01(\x05R\aspellId\"\xd5\x02\n" +
	"\vMotionEvent\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\x05R\townerType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\x05R\x06action\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\x05R\tdirection\x12*\n" +
	"\bposition\x18\x05 \x01(\v2\x0e.hbonline.Vec2R\bposition\x120\n" +
	"\vdestination\x18\x06 \x01(\v2\x0e.hbonline.Vec2R\vdestination\x12\x14\n" +
	"\x05speed\x18\a \x01(\x05R\x05speed\x124\n" +
	"\n" +
	"appearance\x18\b \x01(\v2\x14.hbonline.AppearanceR\n" +
	"appearance\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"\xb4\x02\n" +
	"\fPlayerAppear\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\bposition\x18\x03 \x01(\v2\x0e.hbonline.Vec2R\bposition\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\x05R\tdirection\x124\n" +
	"\n" +
	"appearance\x18\x05 \x01(\v2\x14.hbonline.AppearanceR\n" +
	"appearance\x12\x16\n" +
	"\x06action\x18\x06 \x01(\x05R\x06action\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\x12\x12\n" +
	"\x04side\x18\b \x01(\x05R\x04side\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x19\n" +
	"\bpk_count\x18\n" +
	" \x01(\x05R\apkCount\".\n" +
	"\x0fPlayerDisappear\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\"\xd1\x01\n" +
	"\tNpcAppear\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bnpc_type\x18\x03 \x01(\x05R\anpcType\x12*\n" +
	"\bposition\x18\x04 \x01(\v2\x0e.hbonline.Vec2R\bposition\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x05R\tdirection\x12\x16\n" +
	"\x06action\x18\x06 \x01(\x05R\x06action\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"+\n" +
	"\fNpcDisappear\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\"\xd2\x01\n" +
	"\tNpcMotion\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\x05R\x06action\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\x05R\tdirection\x12*\n" +
	"\bposition\x18\x04 \x01(\v2\x0e.hbonline.Vec2R\bposition\x120\n" +
	"\vdestination\x18\x05 \x01(\v2\x0e.hbonline.Vec2R\vdestination\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x05R\x05speed\"<\n" +
	"\fNotification\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\"x\n" +
	"\x11MapChangeResponse\x12\x19\n" +
	"\bmap_name\x18\x01 \x01(\tR\amapName\x12*\n" +
	"\bposition\x18\x02 \x01(\v2\x0e.hbonline.Vec2R\bposition\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\x05R\tdirection\"\xd3\x02\n" +
	"\n" +
	"EntityInfo\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\x05R\n" +
	"entityType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12*\n" +
	"\bposition\x18\x04 \x01(\v2\x0e.hbonline.Vec2R\bposition\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x05R\tdirection\x12\x16\n" +
	"\x06action\x18\x06 \x01(\x05R\x06action\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x124\n" +
	"\n" +
	"appearance\x18\b \x01(\v2\x14.hbonline.AppearanceR\n" +
	"appearance\x12\x19\n" +
	"\bnpc_type\x18\t \x01(\x05R\anpcType\x12\x14\n" +
	"\x05level\x18\n" +
	" \x01(\x05R\x05level\x12\x12\n" +
	"\x04side\x18\v \x01(\x05R\x04sideB0Z.github.com/juanrossi/hbonline/server/pkg/protob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_game_proto_goTypes = []any{
	(*EnterGameResponse)(nil), // 0: hbonline.EnterGameResponse
	(*PlayerContents)(nil),    // 1: hbonline.PlayerContents
	(*MapInfo)(nil),           // 2: hbonline.MapInfo
	(*MotionRequest)(nil),     // 3: hbonline.MotionRequest
	(*MotionEvent)(nil),       // 4: hbonline.MotionEvent
	(*PlayerAppear)(nil),      // 5: hbonline.PlayerAppear
	(*PlayerDisappear)(nil),   // 6: hbonline.PlayerDisappear
	(*NpcAppear)(nil),         // 7: hbonline.NpcAppear
	(*NpcDisappear)(nil),      // 8: hbonline.NpcDisappear
	(*NpcMotion)(nil),         // 9: hbonline.NpcMotion
	(*Notification)(nil),      // 10: hbonline.Notification
	(*MapChangeResponse)(nil), // 11: hbonline.MapChangeResponse
	(*EntityInfo)(nil),        // 12: hbonline.EntityInfo
	(*Vec2)(nil),              // 13: hbonline.Vec2
	(*Appearance)(nil),        // 14: hbonline.Appearance
}
var file_game_proto_depIdxs = []int32{
	1,  // 0: hbonline.EnterGameResponse.player:type_name -> hbonline.PlayerContents
	2,  // 1: hbonline.EnterGameResponse.map_info:type_name -> hbonline.MapInfo
	12, // 2: hbonline.EnterGameResponse.nearby_players:type_name -> hbonline.EntityInfo
	12, // 3: hbonline.EnterGameResponse.nearby_npcs:type_name -> hbonline.EntityInfo
	13, // 4: hbonline.PlayerContents.position:type_name -> hbonline.Vec2
	14, // 5: hbonline.PlayerContents.appearance:type_name -> hbonline.Appearance
	13, // 6: hbonline.MotionRequest.position:type_name -> hbonline.Vec2
	13, // 7: hbonline.MotionEvent.position:type_name -> hbonline.Vec2
	13, // 8: hbonline.MotionEvent.destination:type_name -> hbonline.Vec2
	14, // 9: hbonline.MotionEvent.appearance:type_name -> hbonline.Appearance
	13, // 10: hbonline.PlayerAppear.position:type_name -> hbonline.Vec2
	14, // 11: hbonline.PlayerAppear.appearance:type_name -> hbonline.Appearance
	13, // 12: hbonline.NpcAppear.position:type_name -> hbonline.Vec2
	13, // 13: hbonline.NpcMotion.position:type_name -> hbonline.Vec2
	13, // 14: hbonline.NpcMotion.destination:type_name -> hbonline.Vec2
	13, // 15: hbonline.MapChangeResponse.position:type_name -> hbonline.Vec2
	13, // 16: hbonline.EntityInfo.position:type_name -> hbonline.Vec2
	14, // 17: hbonline.EntityInfo.appearance:type_name -> hbonline.Appearance
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
