// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: items.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An item instance (in inventory, on ground, or equipped)
type ItemInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // item definition ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`           // stack count
	Durability    int32                  `protobuf:"varint,4,opt,name=durability,proto3" json:"durability,omitempty"` // current durability
	MaxDurability int32                  `protobuf:"varint,5,opt,name=max_durability,json=maxDurability,proto3" json:"max_durability,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,6,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"` // inventory slot (0-49) or equip slot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInstance) Reset() {
	*x = ItemInstance{}
	mi := &file_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInstance) ProtoMessage() {}

func (x *ItemInstance) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInstance.ProtoReflect.Descriptor instead.
func (*ItemInstance) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{0}
}

func (x *ItemInstance) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemInstance) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemInstance) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *ItemInstance) GetMaxDurability() int32 {
	if x != nil {
		return x.MaxDurability
	}
	return 0
}

func (x *ItemInstance) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

// Server -> Client: Full inventory state
type InventoryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemInstance        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`         // inventory items (slots 0-49)
	Equipment     []*ItemInstance        `protobuf:"bytes,2,rep,name=equipment,proto3" json:"equipment,omitempty"` // equipped items (7 slots)
	Gold          int64                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryUpdate) Reset() {
	*x = InventoryUpdate{}
	mi := &file_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUpdate) ProtoMessage() {}

func (x *InventoryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUpdate.ProtoReflect.Descriptor instead.
func (*InventoryUpdate) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryUpdate) GetItems() []*ItemInstance {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InventoryUpdate) GetEquipment() []*ItemInstance {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *InventoryUpdate) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

// Server -> Client: An item appeared on the ground
type GroundItemAppear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundId      int32                  `protobuf:"varint,1,opt,name=ground_id,json=groundId,proto3" json:"ground_id,omitempty"` // unique ground item instance ID
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroundItemAppear) Reset() {
	*x = GroundItemAppear{}
	mi := &file_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundItemAppear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundItemAppear) ProtoMessage() {}

func (x *GroundItemAppear) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundItemAppear.ProtoReflect.Descriptor instead.
func (*GroundItemAppear) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{2}
}

func (x *GroundItemAppear) GetGroundId() int32 {
	if x != nil {
		return x.GroundId
	}
	return 0
}

func (x *GroundItemAppear) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GroundItemAppear) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroundItemAppear) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GroundItemAppear) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

// Server -> Client: An item was picked up from the ground
type GroundItemDisappear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundId      int32                  `protobuf:"varint,1,opt,name=ground_id,json=groundId,proto3" json:"ground_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroundItemDisappear) Reset() {
	*x = GroundItemDisappear{}
	mi := &file_items_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundItemDisappear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundItemDisappear) ProtoMessage() {}

func (x *GroundItemDisappear) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundItemDisappear.ProtoReflect.Descriptor instead.
func (*GroundItemDisappear) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{3}
}

func (x *GroundItemDisappear) GetGroundId() int32 {
	if x != nil {
		return x.GroundId
	}
	return 0
}

// Client -> Server: Pick up a ground item
type ItemPickupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundId      int32                  `protobuf:"varint,1,opt,name=ground_id,json=groundId,proto3" json:"ground_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemPickupRequest) Reset() {
	*x = ItemPickupRequest{}
	mi := &file_items_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemPickupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemPickupRequest) ProtoMessage() {}

func (x *ItemPickupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemPickupRequest.ProtoReflect.Descriptor instead.
func (*ItemPickupRequest) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{4}
}

func (x *ItemPickupRequest) GetGroundId() int32 {
	if x != nil {
		return x.GroundId
	}
	return 0
}

// Client -> Server: Use an item (potion, scroll, etc.)
type ItemUseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotIndex     int32                  `protobuf:"varint,1,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"` // inventory slot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUseRequest) Reset() {
	*x = ItemUseRequest{}
	mi := &file_items_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUseRequest) ProtoMessage() {}

func (x *ItemUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUseRequest.ProtoReflect.Descriptor instead.
func (*ItemUseRequest) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{5}
}

func (x *ItemUseRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

// Client -> Server: Equip or unequip an item
type ItemEquipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotIndex     int32                  `protobuf:"varint,1,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"` // inventory slot to equip, or -1 to unequip
	EquipSlot     int32                  `protobuf:"varint,2,opt,name=equip_slot,json=equipSlot,proto3" json:"equip_slot,omitempty"` // equipment slot (1-7)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemEquipRequest) Reset() {
	*x = ItemEquipRequest{}
	mi := &file_items_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemEquipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemEquipRequest) ProtoMessage() {}

func (x *ItemEquipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemEquipRequest.ProtoReflect.Descriptor instead.
func (*ItemEquipRequest) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{6}
}

func (x *ItemEquipRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *ItemEquipRequest) GetEquipSlot() int32 {
	if x != nil {
		return x.EquipSlot
	}
	return 0
}

// Client -> Server: Drop an item on the ground
type ItemDropRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotIndex     int32                  `protobuf:"varint,1,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // how many to drop (for stacks)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDropRequest) Reset() {
	*x = ItemDropRequest{}
	mi := &file_items_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDropRequest) ProtoMessage() {}

func (x *ItemDropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDropRequest.ProtoReflect.Descriptor instead.
func (*ItemDropRequest) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{7}
}

func (x *ItemDropRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *ItemDropRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Client -> Server: Allocate stat points
type StatAllocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      int32                  `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3" json:"stat_type,omitempty"` // 1=STR, 2=VIT, 3=DEX, 4=INT, 5=MAG, 6=CHR
	Points        int32                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`                     // how many points to allocate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatAllocRequest) Reset() {
	*x = StatAllocRequest{}
	mi := &file_items_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatAllocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatAllocRequest) ProtoMessage() {}

func (x *StatAllocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatAllocRequest.ProtoReflect.Descriptor instead.
func (*StatAllocRequest) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{8}
}

func (x *StatAllocRequest) GetStatType() int32 {
	if x != nil {
		return x.StatType
	}
	return 0
}

func (x *StatAllocRequest) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

// Server -> Client: Shop inventory for buy/sell
type ShopOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         int32                  `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	ShopName      string                 `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	Items         []*ShopItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopOpen) Reset() {
	*x = ShopOpen{}
	mi := &file_items_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopOpen) ProtoMessage() {}

func (x *ShopOpen) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopOpen.ProtoReflect.Descriptor instead.
func (*ShopOpen) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{9}
}

func (x *ShopOpen) GetNpcId() int32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *ShopOpen) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ShopOpen) GetItems() []*ShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShopItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ItemType      int32                  `protobuf:"varint,4,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // for display categorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_items_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{10}
}

func (x *ShopItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ShopItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ShopItem) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

// Client -> Server: Buy from shop
type ShopBuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         int32                  `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopBuyRequest) Reset() {
	*x = ShopBuyRequest{}
	mi := &file_items_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopBuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopBuyRequest) ProtoMessage() {}

func (x *ShopBuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopBuyRequest.ProtoReflect.Descriptor instead.
func (*ShopBuyRequest) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{11}
}

func (x *ShopBuyRequest) GetNpcId() int32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *ShopBuyRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ShopBuyRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Client -> Server: Sell to shop
type ShopSellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         int32                  `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,2,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"` // inventory slot
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopSellRequest) Reset() {
	*x = ShopSellRequest{}
	mi := &file_items_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopSellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopSellRequest) ProtoMessage() {}

func (x *ShopSellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopSellRequest.ProtoReflect.Descriptor instead.
func (*ShopSellRequest) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{12}
}

func (x *ShopSellRequest) GetNpcId() int32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *ShopSellRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *ShopSellRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Server -> Client: Shop transaction result
type ShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopResponse) Reset() {
	*x = ShopResponse{}
	mi := &file_items_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopResponse) ProtoMessage() {}

func (x *ShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopResponse.ProtoReflect.Descriptor instead.
func (*ShopResponse) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{13}
}

func (x *ShopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_items_proto protoreflect.FileDescriptor

const file_items_proto_rawDesc = "" +
	"\n" +
	"\vitems.proto\x12\bhbonline\x1a\fcommon.proto\"\xb7\x01\n" +
	"\fItemInstance\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x1e\n" +
	"\n" +
	"durability\x18\x04 \x01(\x05R\n" +
	"durability\x12%\n" +
	"\x0emax_durability\x18\x05 \x01(\x05R\rmaxDurability\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x06 \x01(\x05R\tslotIndex\"\x89\x01\n" +
	"\x0fInventoryUpdate\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.hbonline.ItemInstanceR\x05items\x124\n" +
	"\tequipment\x18\x02 \x03(\v2\x16.hbonline.ItemInstanceR\tequipment\x12\x12\n" +
	"\x04gold\x18\x03 \x01(\x03R\x04gold\"\x9e\x01\n" +
	"\x10GroundItemAppear\x12\x1b\n" +
	"\tground_id\x18\x01 \x01(\x05R\bgroundId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12*\n" +
	"\bposition\x18\x05 \x01(\v2\x0e.hbonline.Vec2R\bposition\"2\n" +
	"\x13GroundItemDisappear\x12\x1b\n" +
	"\tground_id\x18\x01 \x01(\x05R\bgroundId\"0\n" +
	"\x11ItemPickupRequest\x12\x1b\n" +
	"\tground_id\x18\x01 \x01(\x05R\bgroundId\"/\n" +
	"\x0eItemUseRequest\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x01 \x01(\x05R\tslotIndex\"P\n" +
	"\x10ItemEquipRequest\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x01 \x01(\x05R\tslotIndex\x12\x1d\n" +
	"\n" +
	"equip_slot\x18\x02 \x01(\x05R\tequipSlot\"F\n" +
	"\x0fItemDropRequest\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x01 \x01(\x05R\tslotIndex\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"G\n" +
	"\x10StatAllocRequest\x12\x1b\n" +
	"\tstat_type\x18\x01 \x01(\x05R\bstatType\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x05R\x06points\"h\n" +
	"\bShopOpen\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x05R\x05npcId\x12\x1b\n" +
	"\tshop_name\x18\x02 \x01(\tR\bshopName\x12(\n" +
	"\x05items\x18\x03 \x03(\v2\x12.hbonline.ShopItemR\x05items\"j\n" +
	"\bShopItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1b\n" +
	"\titem_type\x18\x04 \x01(\x05R\bitemType\"V\n" +
	"\x0eShopBuyRequest\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x05R\x05npcId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"]\n" +
	"\x0fShopSellRequest\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x05R\x05npcId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x02 \x01(\x05R\tslotIndex\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\">\n" +
	"\fShopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB0Z.github.com/juanrossi/hbonline/server/pkg/protob\x06proto3"

var (
	file_items_proto_rawDescOnce sync.Once
	file_items_proto_rawDescData []byte
)

func file_items_proto_rawDescGZIP() []byte {
	file_items_proto_rawDescOnce.Do(func() {
		file_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_items_proto_rawDesc), len(file_items_proto_rawDesc)))
	})
	return file_items_proto_rawDescData
}

var file_items_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_items_proto_goTypes = []any{
	(*ItemInstance)(nil),        // 0: hbonline.ItemInstance
	(*InventoryUpdate)(nil),     // 1: hbonline.InventoryUpdate
	(*GroundItemAppear)(nil),    // 2: hbonline.GroundItemAppear
	(*GroundItemDisappear)(nil), // 3: hbonline.GroundItemDisappear
	(*ItemPickupRequest)(nil),   // 4: hbonline.ItemPickupRequest
	(*ItemUseRequest)(nil),      // 5: hbonline.ItemUseRequest
	(*ItemEquipRequest)(nil),    // 6: hbonline.ItemEquipRequest
	(*ItemDropRequest)(nil),     // 7: hbonline.ItemDropRequest
	(*StatAllocRequest)(nil),    // 8: hbonline.StatAllocRequest
	(*ShopOpen)(nil),            // 9: hbonline.ShopOpen
	(*ShopItem)(nil),            // 10: hbonline.ShopItem
	(*ShopBuyRequest)(nil),      // 11: hbonline.ShopBuyRequest
	(*ShopSellRequest)(nil),     // 12: hbonline.ShopSellRequest
	(*ShopResponse)(nil),        // 13: hbonline.ShopResponse
	(*Vec2)(nil),                // 14: hbonline.Vec2
}
var file_items_proto_depIdxs = []int32{
	0,  // 0: hbonline.InventoryUpdate.items:type_name -> hbonline.ItemInstance
	0,  // 1: hbonline.InventoryUpdate.equipment:type_name -> hbonline.ItemInstance
	14, // 2: hbonline.GroundItemAppear.position:type_name -> hbonline.Vec2
	10, // 3: hbonline.ShopOpen.items:type_name -> hbonline.ShopItem
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_items_proto_init() }
func file_items_proto_init() {
	if File_items_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_items_proto_rawDesc), len(file_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_items_proto_goTypes,
		DependencyIndexes: file_items_proto_depIdxs,
		MessageInfos:      file_items_proto_msgTypes,
	}.Build()
	File_items_proto = out.File
	file_items_proto_goTypes = nil
	file_items_proto_depIdxs = nil
}
