// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: magic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client -> Server: Cast a spell
type SpellCastRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpellId        int32                  `protobuf:"varint,1,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`                     // spell definition ID
	TargetId       int32                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                  // target object ID (0 for self/position-targeted)
	TargetPosition *Vec2                  `protobuf:"bytes,3,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"` // target tile for AOE spells
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpellCastRequest) Reset() {
	*x = SpellCastRequest{}
	mi := &file_magic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellCastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellCastRequest) ProtoMessage() {}

func (x *SpellCastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellCastRequest.ProtoReflect.Descriptor instead.
func (*SpellCastRequest) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{0}
}

func (x *SpellCastRequest) GetSpellId() int32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

func (x *SpellCastRequest) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SpellCastRequest) GetTargetPosition() *Vec2 {
	if x != nil {
		return x.TargetPosition
	}
	return nil
}

// Server -> Client: Spell effect visual (broadcast to nearby)
type SpellEffectEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CasterId       int32                  `protobuf:"varint,1,opt,name=caster_id,json=casterId,proto3" json:"caster_id,omitempty"`
	SpellId        int32                  `protobuf:"varint,2,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	TargetId       int32                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	CasterPosition *Vec2                  `protobuf:"bytes,4,opt,name=caster_position,json=casterPosition,proto3" json:"caster_position,omitempty"`
	TargetPosition *Vec2                  `protobuf:"bytes,5,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	Damage         int32                  `protobuf:"varint,6,opt,name=damage,proto3" json:"damage,omitempty"`                           // 0 for non-damage spells
	HealAmount     int32                  `protobuf:"varint,7,opt,name=heal_amount,json=healAmount,proto3" json:"heal_amount,omitempty"` // 0 for non-heal spells
	Miss           bool                   `protobuf:"varint,8,opt,name=miss,proto3" json:"miss,omitempty"`
	SpriteId       int32                  `protobuf:"varint,9,opt,name=sprite_id,json=spriteId,proto3" json:"sprite_id,omitempty"` // spell effect sprite
	SoundId        int32                  `protobuf:"varint,10,opt,name=sound_id,json=soundId,proto3" json:"sound_id,omitempty"`   // spell sound effect
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpellEffectEvent) Reset() {
	*x = SpellEffectEvent{}
	mi := &file_magic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellEffectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellEffectEvent) ProtoMessage() {}

func (x *SpellEffectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellEffectEvent.ProtoReflect.Descriptor instead.
func (*SpellEffectEvent) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{1}
}

func (x *SpellEffectEvent) GetCasterId() int32 {
	if x != nil {
		return x.CasterId
	}
	return 0
}

func (x *SpellEffectEvent) GetSpellId() int32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

func (x *SpellEffectEvent) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SpellEffectEvent) GetCasterPosition() *Vec2 {
	if x != nil {
		return x.CasterPosition
	}
	return nil
}

func (x *SpellEffectEvent) GetTargetPosition() *Vec2 {
	if x != nil {
		return x.TargetPosition
	}
	return nil
}

func (x *SpellEffectEvent) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *SpellEffectEvent) GetHealAmount() int32 {
	if x != nil {
		return x.HealAmount
	}
	return 0
}

func (x *SpellEffectEvent) GetMiss() bool {
	if x != nil {
		return x.Miss
	}
	return false
}

func (x *SpellEffectEvent) GetSpriteId() int32 {
	if x != nil {
		return x.SpriteId
	}
	return 0
}

func (x *SpellEffectEvent) GetSoundId() int32 {
	if x != nil {
		return x.SoundId
	}
	return 0
}

// Server -> Client: Buff/debuff applied or removed
type BuffUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObjectId         int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"` // who has the buff
	SpellId          int32                  `protobuf:"varint,2,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`    // which spell created it
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                          // buff name
	StatType         int32                  `protobuf:"varint,4,opt,name=stat_type,json=statType,proto3" json:"stat_type,omitempty"` // which stat (1=STR, 2=VIT, 3=DEX, 4=INT, 5=MAG)
	Amount           int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                     // +/- modifier
	RemainingSeconds int32                  `protobuf:"varint,6,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"`
	Removed          bool                   `protobuf:"varint,7,opt,name=removed,proto3" json:"removed,omitempty"` // true = buff expired/was removed
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BuffUpdate) Reset() {
	*x = BuffUpdate{}
	mi := &file_magic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffUpdate) ProtoMessage() {}

func (x *BuffUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffUpdate.ProtoReflect.Descriptor instead.
func (*BuffUpdate) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{2}
}

func (x *BuffUpdate) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *BuffUpdate) GetSpellId() int32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

func (x *BuffUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuffUpdate) GetStatType() int32 {
	if x != nil {
		return x.StatType
	}
	return 0
}

func (x *BuffUpdate) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BuffUpdate) GetRemainingSeconds() int32 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

func (x *BuffUpdate) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// Server -> Client: Full list of player's learned spells
type SpellListUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spells        []*LearnedSpell        `protobuf:"bytes,1,rep,name=spells,proto3" json:"spells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpellListUpdate) Reset() {
	*x = SpellListUpdate{}
	mi := &file_magic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellListUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellListUpdate) ProtoMessage() {}

func (x *SpellListUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellListUpdate.ProtoReflect.Descriptor instead.
func (*SpellListUpdate) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{3}
}

func (x *SpellListUpdate) GetSpells() []*LearnedSpell {
	if x != nil {
		return x.Spells
	}
	return nil
}

type LearnedSpell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpellId       int32                  `protobuf:"varint,1,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ManaCost      int32                  `protobuf:"varint,3,opt,name=mana_cost,json=manaCost,proto3" json:"mana_cost,omitempty"`
	CooldownMs    int32                  `protobuf:"varint,4,opt,name=cooldown_ms,json=cooldownMs,proto3" json:"cooldown_ms,omitempty"`
	SpellType     int32                  `protobuf:"varint,5,opt,name=spell_type,json=spellType,proto3" json:"spell_type,omitempty"` // 1=damage, 2=aoe, 3=heal, 4=buff, 5=debuff
	SpriteId      int32                  `protobuf:"varint,6,opt,name=sprite_id,json=spriteId,proto3" json:"sprite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnedSpell) Reset() {
	*x = LearnedSpell{}
	mi := &file_magic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnedSpell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnedSpell) ProtoMessage() {}

func (x *LearnedSpell) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnedSpell.ProtoReflect.Descriptor instead.
func (*LearnedSpell) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{4}
}

func (x *LearnedSpell) GetSpellId() int32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

func (x *LearnedSpell) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LearnedSpell) GetManaCost() int32 {
	if x != nil {
		return x.ManaCost
	}
	return 0
}

func (x *LearnedSpell) GetCooldownMs() int32 {
	if x != nil {
		return x.CooldownMs
	}
	return 0
}

func (x *LearnedSpell) GetSpellType() int32 {
	if x != nil {
		return x.SpellType
	}
	return 0
}

func (x *LearnedSpell) GetSpriteId() int32 {
	if x != nil {
		return x.SpriteId
	}
	return 0
}

// Client -> Server: Learn a spell (from scroll/NPC)
type LearnSpellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpellId       int32                  `protobuf:"varint,1,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnSpellRequest) Reset() {
	*x = LearnSpellRequest{}
	mi := &file_magic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnSpellRequest) ProtoMessage() {}

func (x *LearnSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnSpellRequest.ProtoReflect.Descriptor instead.
func (*LearnSpellRequest) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{5}
}

func (x *LearnSpellRequest) GetSpellId() int32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

// Server -> Client: Full list of player's skills
type SkillListUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*SkillEntry          `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	TotalMastery  int32                  `protobuf:"varint,2,opt,name=total_mastery,json=totalMastery,proto3" json:"total_mastery,omitempty"` // sum of all skill masteries
	MasteryCap    int32                  `protobuf:"varint,3,opt,name=mastery_cap,json=masteryCap,proto3" json:"mastery_cap,omitempty"`       // 700
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillListUpdate) Reset() {
	*x = SkillListUpdate{}
	mi := &file_magic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillListUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillListUpdate) ProtoMessage() {}

func (x *SkillListUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillListUpdate.ProtoReflect.Descriptor instead.
func (*SkillListUpdate) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{6}
}

func (x *SkillListUpdate) GetSkills() []*SkillEntry {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *SkillListUpdate) GetTotalMastery() int32 {
	if x != nil {
		return x.TotalMastery
	}
	return 0
}

func (x *SkillListUpdate) GetMasteryCap() int32 {
	if x != nil {
		return x.MasteryCap
	}
	return 0
}

type SkillEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int32                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mastery       int32                  `protobuf:"varint,3,opt,name=mastery,proto3" json:"mastery,omitempty"` // 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillEntry) Reset() {
	*x = SkillEntry{}
	mi := &file_magic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillEntry) ProtoMessage() {}

func (x *SkillEntry) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillEntry.ProtoReflect.Descriptor instead.
func (*SkillEntry) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{7}
}

func (x *SkillEntry) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillEntry) GetMastery() int32 {
	if x != nil {
		return x.Mastery
	}
	return 0
}

// Client -> Server: Use a skill (mining, fishing, etc.)
type SkillUseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SkillId        int32                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	TargetPosition *Vec2                  `protobuf:"bytes,2,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"` // target tile
	TargetId       int32                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                  // target object (for crafting stations)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SkillUseRequest) Reset() {
	*x = SkillUseRequest{}
	mi := &file_magic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillUseRequest) ProtoMessage() {}

func (x *SkillUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillUseRequest.ProtoReflect.Descriptor instead.
func (*SkillUseRequest) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{8}
}

func (x *SkillUseRequest) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillUseRequest) GetTargetPosition() *Vec2 {
	if x != nil {
		return x.TargetPosition
	}
	return nil
}

func (x *SkillUseRequest) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// Server -> Client: Skill use result
type SkillResultEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int32                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	NewMastery    int32                  `protobuf:"varint,4,opt,name=new_mastery,json=newMastery,proto3" json:"new_mastery,omitempty"`         // updated mastery level
	ItemGainedId  int32                  `protobuf:"varint,5,opt,name=item_gained_id,json=itemGainedId,proto3" json:"item_gained_id,omitempty"` // item produced (0 if none)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillResultEvent) Reset() {
	*x = SkillResultEvent{}
	mi := &file_magic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillResultEvent) ProtoMessage() {}

func (x *SkillResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillResultEvent.ProtoReflect.Descriptor instead.
func (*SkillResultEvent) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{9}
}

func (x *SkillResultEvent) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillResultEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SkillResultEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SkillResultEvent) GetNewMastery() int32 {
	if x != nil {
		return x.NewMastery
	}
	return 0
}

func (x *SkillResultEvent) GetItemGainedId() int32 {
	if x != nil {
		return x.ItemGainedId
	}
	return 0
}

// Client -> Server: Craft an item
type CraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      int32                  `protobuf:"varint,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CraftRequest) Reset() {
	*x = CraftRequest{}
	mi := &file_magic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CraftRequest) ProtoMessage() {}

func (x *CraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CraftRequest.ProtoReflect.Descriptor instead.
func (*CraftRequest) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{10}
}

func (x *CraftRequest) GetRecipeId() int32 {
	if x != nil {
		return x.RecipeId
	}
	return 0
}

// Server -> Client: Craft result
type CraftResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ItemId        int32                  `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // item produced (0 on failure)
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CraftResult) Reset() {
	*x = CraftResult{}
	mi := &file_magic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CraftResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CraftResult) ProtoMessage() {}

func (x *CraftResult) ProtoReflect() protoreflect.Message {
	mi := &file_magic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CraftResult.ProtoReflect.Descriptor instead.
func (*CraftResult) Descriptor() ([]byte, []int) {
	return file_magic_proto_rawDescGZIP(), []int{11}
}

func (x *CraftResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CraftResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CraftResult) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CraftResult) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_magic_proto protoreflect.FileDescriptor

const file_magic_proto_rawDesc = "" +
	"\n" +
	"\vmagic.proto\x12\bhbonline\x1a\fcommon.proto\"\x83\x01\n" +
	"\x10SpellCastRequest\x12\x19\n" +
	"\bspell_id\x18\x01 \x01(\x05R\aspellId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x05R\btargetId\x127\n" +
	"\x0ftarget_position\x18\x03 \x01(\v2\x0e.hbonline.Vec2R\x0etargetPosition\"\xde\x02\n" +
	"\x10SpellEffectEvent\x12\x1b\n" +
	"\tcaster_id\x18\x01 \x01(\x05R\bcasterId\x12\x19\n" +
	"\bspell_id\x18\x02 \x01(\x05R\aspellId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x05R\btargetId\x127\n" +
	"\x0fcaster_position\x18\x04 \x01(\v2\x0e.hbonline.Vec2R\x0ecasterPosition\x127\n" +
	"\x0ftarget_position\x18\x05 \x01(\v2\x0e.hbonline.Vec2R\x0etargetPosition\x12\x16\n" +
	"\x06damage\x18\x06 \x01(\x05R\x06damage\x12\x1f\n" +
	"\vheal_amount\x18\a \x01(\x05R\n" +
	"healAmount\x12\x12\n" +
	"\x04miss\x18\b \x01(\bR\x04miss\x12\x1b\n" +
	"\tsprite_id\x18\t \x01(\x05R\bspriteId\x12\x19\n" +
	"\bsound_id\x18\n" +
	" \x01(\x05R\asoundId\"\xd4\x01\n" +
	"\n" +
	"BuffUpdate\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\x12\x19\n" +
	"\bspell_id\x18\x02 \x01(\x05R\aspellId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tstat_type\x18\x04 \x01(\x05R\bstatType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12+\n" +
	"\x11remaining_seconds\x18\x06 \x01(\x05R\x10remainingSeconds\x12\x18\n" +
	"\aremoved\x18\a \x01(\bR\aremoved\"A\n" +
	"\x0fSpellListUpdate\x12.\n" +
	"\x06spells\x18\x01 \x03(\v2\x16.hbonline.LearnedSpellR\x06spells\"\xb7\x01\n" +
	"\fLearnedSpell\x12\x19\n" +
	"\bspell_id\x18\x01 \x01(\x05R\aspellId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tmana_cost\x18\x03 \x01(\x05R\bmanaCost\x12\x1f\n" +
	"\vcooldown_ms\x18\x04 \x01(\x05R\n" +
	"cooldownMs\x12\x1d\n" +
	"\n" +
	"spell_type\x18\x05 \x01(\x05R\tspellType\x12\x1b\n" +
	"\tsprite_id\x18\x06 \x01(\x05R\bspriteId\".\n" +
	"\x11LearnSpellRequest\x12\x19\n" +
	"\bspell_id\x18\x01 \x01(\x05R\aspellId\"\x85\x01\n" +
	"\x0fSkillListUpdate\x12,\n" +
	"\x06skills\x18\x01 \x03(\v2\x14.hbonline.SkillEntryR\x06skills\x12#\n" +
	"\rtotal_mastery\x18\x02 \x01(\x05R\ftotalMastery\x12\x1f\n" +
	"\vmastery_cap\x18\x03 \x01(\x05R\n" +
	"masteryCap\"U\n" +
	"\n" +
	"SkillEntry\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x05R\askillId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amastery\x18\x03 \x01(\x05R\amastery\"\x82\x01\n" +
	"\x0fSkillUseRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x05R\askillId\x127\n" +
	"\x0ftarget_position\x18\x02 \x01(\v2\x0e.hbonline.Vec2R\x0etargetPosition\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x05R\btargetId\"\xa8\x01\n" +
	"\x10SkillResultEvent\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x05R\askillId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vnew_mastery\x18\x04 \x01(\x05R\n" +
	"newMastery\x12$\n" +
	"\x0eitem_gained_id\x18\x05 \x01(\x05R\fitemGainedId\"+\n" +
	"\fCraftRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\x05R\brecipeId\"p\n" +
	"\vCraftResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05countB0Z.github.com/juanrossi/hbonline/server/pkg/protob\x06proto3"

var (
	file_magic_proto_rawDescOnce sync.Once
	file_magic_proto_rawDescData []byte
)

func file_magic_proto_rawDescGZIP() []byte {
	file_magic_proto_rawDescOnce.Do(func() {
		file_magic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_magic_proto_rawDesc), len(file_magic_proto_rawDesc)))
	})
	return file_magic_proto_rawDescData
}

var file_magic_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_magic_proto_goTypes = []any{
	(*SpellCastRequest)(nil),  // 0: hbonline.SpellCastRequest
	(*SpellEffectEvent)(nil),  // 1: hbonline.SpellEffectEvent
	(*BuffUpdate)(nil),        // 2: hbonline.BuffUpdate
	(*SpellListUpdate)(nil),   // 3: hbonline.SpellListUpdate
	(*LearnedSpell)(nil),      // 4: hbonline.LearnedSpell
	(*LearnSpellRequest)(nil), // 5: hbonline.LearnSpellRequest
	(*SkillListUpdate)(nil),   // 6: hbonline.SkillListUpdate
	(*SkillEntry)(nil),        // 7: hbonline.SkillEntry
	(*SkillUseRequest)(nil),   // 8: hbonline.SkillUseRequest
	(*SkillResultEvent)(nil),  // 9: hbonline.SkillResultEvent
	(*CraftRequest)(nil),      // 10: hbonline.CraftRequest
	(*CraftResult)(nil),       // 11: hbonline.CraftResult
	(*Vec2)(nil),              // 12: hbonline.Vec2
}
var file_magic_proto_depIdxs = []int32{
	12, // 0: hbonline.SpellCastRequest.target_position:type_name -> hbonline.Vec2
	12, // 1: hbonline.SpellEffectEvent.caster_position:type_name -> hbonline.Vec2
	12, // 2: hbonline.SpellEffectEvent.target_position:type_name -> hbonline.Vec2
	4,  // 3: hbonline.SpellListUpdate.spells:type_name -> hbonline.LearnedSpell
	7,  // 4: hbonline.SkillListUpdate.skills:type_name -> hbonline.SkillEntry
	12, // 5: hbonline.SkillUseRequest.target_position:type_name -> hbonline.Vec2
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_magic_proto_init() }
func file_magic_proto_init() {
	if File_magic_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_magic_proto_rawDesc), len(file_magic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_magic_proto_goTypes,
		DependencyIndexes: file_magic_proto_depIdxs,
		MessageInfos:      file_magic_proto_msgTypes,
	}.Build()
	File_magic_proto = out.File
	file_magic_proto_goTypes = nil
	file_magic_proto_depIdxs = nil
}
