// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: quest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client -> Server: Accept a quest
type QuestAcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       int32                  `protobuf:"varint,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestAcceptRequest) Reset() {
	*x = QuestAcceptRequest{}
	mi := &file_quest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestAcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestAcceptRequest) ProtoMessage() {}

func (x *QuestAcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestAcceptRequest.ProtoReflect.Descriptor instead.
func (*QuestAcceptRequest) Descriptor() ([]byte, []int) {
	return file_quest_proto_rawDescGZIP(), []int{0}
}

func (x *QuestAcceptRequest) GetQuestId() int32 {
	if x != nil {
		return x.QuestId
	}
	return 0
}

// Client -> Server: Turn in a completed quest
type QuestTurnInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       int32                  `protobuf:"varint,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestTurnInRequest) Reset() {
	*x = QuestTurnInRequest{}
	mi := &file_quest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestTurnInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestTurnInRequest) ProtoMessage() {}

func (x *QuestTurnInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestTurnInRequest.ProtoReflect.Descriptor instead.
func (*QuestTurnInRequest) Descriptor() ([]byte, []int) {
	return file_quest_proto_rawDescGZIP(), []int{1}
}

func (x *QuestTurnInRequest) GetQuestId() int32 {
	if x != nil {
		return x.QuestId
	}
	return 0
}

// Server -> Client: Quest list update
type QuestListUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveQuests      []*QuestEntry          `protobuf:"bytes,1,rep,name=active_quests,json=activeQuests,proto3" json:"active_quests,omitempty"`
	AvailableQuestIds []int32                `protobuf:"varint,2,rep,packed,name=available_quest_ids,json=availableQuestIds,proto3" json:"available_quest_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuestListUpdate) Reset() {
	*x = QuestListUpdate{}
	mi := &file_quest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestListUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestListUpdate) ProtoMessage() {}

func (x *QuestListUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_quest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestListUpdate.ProtoReflect.Descriptor instead.
func (*QuestListUpdate) Descriptor() ([]byte, []int) {
	return file_quest_proto_rawDescGZIP(), []int{2}
}

func (x *QuestListUpdate) GetActiveQuests() []*QuestEntry {
	if x != nil {
		return x.ActiveQuests
	}
	return nil
}

func (x *QuestListUpdate) GetAvailableQuestIds() []int32 {
	if x != nil {
		return x.AvailableQuestIds
	}
	return nil
}

type QuestEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       int32                  `protobuf:"varint,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	QuestType     int32                  `protobuf:"varint,4,opt,name=quest_type,json=questType,proto3" json:"quest_type,omitempty"`
	State         int32                  `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	Progress      int32                  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	TargetCount   int32                  `protobuf:"varint,7,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	RewardXp      int32                  `protobuf:"varint,8,opt,name=reward_xp,json=rewardXp,proto3" json:"reward_xp,omitempty"`
	RewardGold    int64                  `protobuf:"varint,9,opt,name=reward_gold,json=rewardGold,proto3" json:"reward_gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestEntry) Reset() {
	*x = QuestEntry{}
	mi := &file_quest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestEntry) ProtoMessage() {}

func (x *QuestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_quest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestEntry.ProtoReflect.Descriptor instead.
func (*QuestEntry) Descriptor() ([]byte, []int) {
	return file_quest_proto_rawDescGZIP(), []int{3}
}

func (x *QuestEntry) GetQuestId() int32 {
	if x != nil {
		return x.QuestId
	}
	return 0
}

func (x *QuestEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuestEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuestEntry) GetQuestType() int32 {
	if x != nil {
		return x.QuestType
	}
	return 0
}

func (x *QuestEntry) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *QuestEntry) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *QuestEntry) GetTargetCount() int32 {
	if x != nil {
		return x.TargetCount
	}
	return 0
}

func (x *QuestEntry) GetRewardXp() int32 {
	if x != nil {
		return x.RewardXp
	}
	return 0
}

func (x *QuestEntry) GetRewardGold() int64 {
	if x != nil {
		return x.RewardGold
	}
	return 0
}

// Server -> Client: Quest progress update
type QuestProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       int32                  `protobuf:"varint,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	TargetCount   int32                  `protobuf:"varint,3,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	Completed     bool                   `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestProgressUpdate) Reset() {
	*x = QuestProgressUpdate{}
	mi := &file_quest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestProgressUpdate) ProtoMessage() {}

func (x *QuestProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_quest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestProgressUpdate.ProtoReflect.Descriptor instead.
func (*QuestProgressUpdate) Descriptor() ([]byte, []int) {
	return file_quest_proto_rawDescGZIP(), []int{4}
}

func (x *QuestProgressUpdate) GetQuestId() int32 {
	if x != nil {
		return x.QuestId
	}
	return 0
}

func (x *QuestProgressUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *QuestProgressUpdate) GetTargetCount() int32 {
	if x != nil {
		return x.TargetCount
	}
	return 0
}

func (x *QuestProgressUpdate) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

// Server -> Client: Quest completion reward
type QuestRewardNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       int32                  `protobuf:"varint,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	QuestName     string                 `protobuf:"bytes,2,opt,name=quest_name,json=questName,proto3" json:"quest_name,omitempty"`
	XpGained      int64                  `protobuf:"varint,3,opt,name=xp_gained,json=xpGained,proto3" json:"xp_gained,omitempty"`
	GoldGained    int64                  `protobuf:"varint,4,opt,name=gold_gained,json=goldGained,proto3" json:"gold_gained,omitempty"`
	ItemId        int32                  `protobuf:"varint,5,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemCount     int32                  `protobuf:"varint,6,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestRewardNotification) Reset() {
	*x = QuestRewardNotification{}
	mi := &file_quest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestRewardNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestRewardNotification) ProtoMessage() {}

func (x *QuestRewardNotification) ProtoReflect() protoreflect.Message {
	mi := &file_quest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestRewardNotification.ProtoReflect.Descriptor instead.
func (*QuestRewardNotification) Descriptor() ([]byte, []int) {
	return file_quest_proto_rawDescGZIP(), []int{5}
}

func (x *QuestRewardNotification) GetQuestId() int32 {
	if x != nil {
		return x.QuestId
	}
	return 0
}

func (x *QuestRewardNotification) GetQuestName() string {
	if x != nil {
		return x.QuestName
	}
	return ""
}

func (x *QuestRewardNotification) GetXpGained() int64 {
	if x != nil {
		return x.XpGained
	}
	return 0
}

func (x *QuestRewardNotification) GetGoldGained() int64 {
	if x != nil {
		return x.GoldGained
	}
	return 0
}

func (x *QuestRewardNotification) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *QuestRewardNotification) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

var File_quest_proto protoreflect.FileDescriptor

const file_quest_proto_rawDesc = "" +
	"\n" +
	"\vquest.proto\x12\bhbonline\"/\n" +
	"\x12QuestAcceptRequest\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\x05R\aquestId\"/\n" +
	"\x12QuestTurnInRequest\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\x05R\aquestId\"|\n" +
	"\x0fQuestListUpdate\x129\n" +
	"\ractive_quests\x18\x01 \x03(\v2\x14.hbonline.QuestEntryR\factiveQuests\x12.\n" +
	"\x13available_quest_ids\x18\x02 \x03(\x05R\x11availableQuestIds\"\x8f\x02\n" +
	"\n" +
	"QuestEntry\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\x05R\aquestId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"quest_type\x18\x04 \x01(\x05R\tquestType\x12\x14\n" +
	"\x05state\x18\x05 \x01(\x05R\x05state\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\x12!\n" +
	"\ftarget_count\x18\a \x01(\x05R\vtargetCount\x12\x1b\n" +
	"\treward_xp\x18\b \x01(\x05R\brewardXp\x12\x1f\n" +
	"\vreward_gold\x18\t \x01(\x03R\n" +
	"rewardGold\"\x8d\x01\n" +
	"\x13QuestProgressUpdate\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\x05R\aquestId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12!\n" +
	"\ftarget_count\x18\x03 \x01(\x05R\vtargetCount\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\"\xc9\x01\n" +
	"\x17QuestRewardNotification\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\x05R\aquestId\x12\x1d\n" +
	"\n" +
	"quest_name\x18\x02 \x01(\tR\tquestName\x12\x1b\n" +
	"\txp_gained\x18\x03 \x01(\x03R\bxpGained\x12\x1f\n" +
	"\vgold_gained\x18\x04 \x01(\x03R\n" +
	"goldGained\x12\x17\n" +
	"\aitem_id\x18\x05 \x01(\x05R\x06itemId\x12\x1d\n" +
	"\n" +
	"item_count\x18\x06 \x01(\x05R\titemCountB0Z.github.com/juanrossi/hbonline/server/pkg/protob\x06proto3"

var (
	file_quest_proto_rawDescOnce sync.Once
	file_quest_proto_rawDescData []byte
)

func file_quest_proto_rawDescGZIP() []byte {
	file_quest_proto_rawDescOnce.Do(func() {
		file_quest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quest_proto_rawDesc), len(file_quest_proto_rawDesc)))
	})
	return file_quest_proto_rawDescData
}

var file_quest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_quest_proto_goTypes = []any{
	(*QuestAcceptRequest)(nil),      // 0: hbonline.QuestAcceptRequest
	(*QuestTurnInRequest)(nil),      // 1: hbonline.QuestTurnInRequest
	(*QuestListUpdate)(nil),         // 2: hbonline.QuestListUpdate
	(*QuestEntry)(nil),              // 3: hbonline.QuestEntry
	(*QuestProgressUpdate)(nil),     // 4: hbonline.QuestProgressUpdate
	(*QuestRewardNotification)(nil), // 5: hbonline.QuestRewardNotification
}
var file_quest_proto_depIdxs = []int32{
	3, // 0: hbonline.QuestListUpdate.active_quests:type_name -> hbonline.QuestEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quest_proto_init() }
func file_quest_proto_init() {
	if File_quest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quest_proto_rawDesc), len(file_quest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quest_proto_goTypes,
		DependencyIndexes: file_quest_proto_depIdxs,
		MessageInfos:      file_quest_proto_msgTypes,
	}.Build()
	File_quest_proto = out.File
	file_quest_proto_goTypes = nil
	file_quest_proto_depIdxs = nil
}
