// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: social.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client -> Server: Choose a faction
type FactionSelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          int32                  `protobuf:"varint,1,opt,name=side,proto3" json:"side,omitempty"` // 1=Aresden, 2=Elvine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactionSelectRequest) Reset() {
	*x = FactionSelectRequest{}
	mi := &file_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactionSelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactionSelectRequest) ProtoMessage() {}

func (x *FactionSelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactionSelectRequest.ProtoReflect.Descriptor instead.
func (*FactionSelectRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{0}
}

func (x *FactionSelectRequest) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

// Server -> Client: Faction selection result
type FactionSelectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Side          int32                  `protobuf:"varint,3,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactionSelectResponse) Reset() {
	*x = FactionSelectResponse{}
	mi := &file_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactionSelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactionSelectResponse) ProtoMessage() {}

func (x *FactionSelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactionSelectResponse.ProtoReflect.Descriptor instead.
func (*FactionSelectResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{1}
}

func (x *FactionSelectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FactionSelectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FactionSelectResponse) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

// Client -> Server: Create a guild
type GuildCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildCreateRequest) Reset() {
	*x = GuildCreateRequest{}
	mi := &file_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildCreateRequest) ProtoMessage() {}

func (x *GuildCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildCreateRequest.ProtoReflect.Descriptor instead.
func (*GuildCreateRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{2}
}

func (x *GuildCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Client -> Server: Guild management action
type GuildActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        int32                  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"` // 1=invite, 2=kick, 3=promote, 4=demote, 5=leave, 6=disband
	TargetName    string                 `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildActionRequest) Reset() {
	*x = GuildActionRequest{}
	mi := &file_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildActionRequest) ProtoMessage() {}

func (x *GuildActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildActionRequest.ProtoReflect.Descriptor instead.
func (*GuildActionRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{3}
}

func (x *GuildActionRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *GuildActionRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

// Server -> Client: Guild info update
type GuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       int32                  `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Side          int32                  `protobuf:"varint,3,opt,name=side,proto3" json:"side,omitempty"`
	Members       []*GuildMemberInfo     `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	MasterName    string                 `protobuf:"bytes,5,opt,name=master_name,json=masterName,proto3" json:"master_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildInfo) Reset() {
	*x = GuildInfo{}
	mi := &file_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildInfo) ProtoMessage() {}

func (x *GuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildInfo.ProtoReflect.Descriptor instead.
func (*GuildInfo) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{4}
}

func (x *GuildInfo) GetGuildId() int32 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildInfo) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *GuildInfo) GetMembers() []*GuildMemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GuildInfo) GetMasterName() string {
	if x != nil {
		return x.MasterName
	}
	return ""
}

type GuildMemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"` // 1=member, 2=officer, 3=master
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Online        bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildMemberInfo) Reset() {
	*x = GuildMemberInfo{}
	mi := &file_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMemberInfo) ProtoMessage() {}

func (x *GuildMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMemberInfo.ProtoReflect.Descriptor instead.
func (*GuildMemberInfo) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{5}
}

func (x *GuildMemberInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildMemberInfo) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GuildMemberInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GuildMemberInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// Server -> Client: Guild action result
type GuildActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildActionResponse) Reset() {
	*x = GuildActionResponse{}
	mi := &file_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildActionResponse) ProtoMessage() {}

func (x *GuildActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildActionResponse.ProtoReflect.Descriptor instead.
func (*GuildActionResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{6}
}

func (x *GuildActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GuildActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Client -> Server: Party action
type PartyActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        int32                  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"` // 1=invite, 2=kick, 3=leave
	TargetName    string                 `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyActionRequest) Reset() {
	*x = PartyActionRequest{}
	mi := &file_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyActionRequest) ProtoMessage() {}

func (x *PartyActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyActionRequest.ProtoReflect.Descriptor instead.
func (*PartyActionRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{7}
}

func (x *PartyActionRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *PartyActionRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

// Server -> Client: Party action result
type PartyActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyActionResponse) Reset() {
	*x = PartyActionResponse{}
	mi := &file_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyActionResponse) ProtoMessage() {}

func (x *PartyActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyActionResponse.ProtoReflect.Descriptor instead.
func (*PartyActionResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{8}
}

func (x *PartyActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PartyActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Server -> Client: Party member list
type PartyUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Members        []*PartyMemberInfo     `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	LeaderObjectId int32                  `protobuf:"varint,2,opt,name=leader_object_id,json=leaderObjectId,proto3" json:"leader_object_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartyUpdate) Reset() {
	*x = PartyUpdate{}
	mi := &file_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyUpdate) ProtoMessage() {}

func (x *PartyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyUpdate.ProtoReflect.Descriptor instead.
func (*PartyUpdate) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{9}
}

func (x *PartyUpdate) GetMembers() []*PartyMemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *PartyUpdate) GetLeaderObjectId() int32 {
	if x != nil {
		return x.LeaderObjectId
	}
	return 0
}

type PartyMemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int32                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int32                  `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyMemberInfo) Reset() {
	*x = PartyMemberInfo{}
	mi := &file_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyMemberInfo) ProtoMessage() {}

func (x *PartyMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyMemberInfo.ProtoReflect.Descriptor instead.
func (*PartyMemberInfo) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{10}
}

func (x *PartyMemberInfo) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *PartyMemberInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartyMemberInfo) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PartyMemberInfo) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PartyMemberInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Server -> Client: Party invite received
type PartyInvite struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InviterObjectId int32                  `protobuf:"varint,1,opt,name=inviter_object_id,json=inviterObjectId,proto3" json:"inviter_object_id,omitempty"`
	InviterName     string                 `protobuf:"bytes,2,opt,name=inviter_name,json=inviterName,proto3" json:"inviter_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartyInvite) Reset() {
	*x = PartyInvite{}
	mi := &file_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInvite) ProtoMessage() {}

func (x *PartyInvite) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInvite.ProtoReflect.Descriptor instead.
func (*PartyInvite) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{11}
}

func (x *PartyInvite) GetInviterObjectId() int32 {
	if x != nil {
		return x.InviterObjectId
	}
	return 0
}

func (x *PartyInvite) GetInviterName() string {
	if x != nil {
		return x.InviterName
	}
	return ""
}

// Client -> Server: Accept/decline party invite
type PartyInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accept        bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyInviteResponse) Reset() {
	*x = PartyInviteResponse{}
	mi := &file_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInviteResponse) ProtoMessage() {}

func (x *PartyInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInviteResponse.ProtoReflect.Descriptor instead.
func (*PartyInviteResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{12}
}

func (x *PartyInviteResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

// Client -> Server: Request trade with another player
type TradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int32                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeRequest) Reset() {
	*x = TradeRequest{}
	mi := &file_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRequest) ProtoMessage() {}

func (x *TradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRequest.ProtoReflect.Descriptor instead.
func (*TradeRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{13}
}

func (x *TradeRequest) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// Server -> Client: Incoming trade request
type TradeIncoming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int32                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	RequesterName string                 `protobuf:"bytes,2,opt,name=requester_name,json=requesterName,proto3" json:"requester_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeIncoming) Reset() {
	*x = TradeIncoming{}
	mi := &file_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeIncoming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeIncoming) ProtoMessage() {}

func (x *TradeIncoming) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeIncoming.ProtoReflect.Descriptor instead.
func (*TradeIncoming) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{14}
}

func (x *TradeIncoming) GetRequesterId() int32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *TradeIncoming) GetRequesterName() string {
	if x != nil {
		return x.RequesterName
	}
	return ""
}

// Client -> Server: Accept or decline trade
type TradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accept        bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeResponse) Reset() {
	*x = TradeResponse{}
	mi := &file_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponse) ProtoMessage() {}

func (x *TradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponse.ProtoReflect.Descriptor instead.
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{15}
}

func (x *TradeResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

// Client -> Server: Set item in trade slot
type TradeSetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventorySlot int32                  `protobuf:"varint,1,opt,name=inventory_slot,json=inventorySlot,proto3" json:"inventory_slot,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeSetItem) Reset() {
	*x = TradeSetItem{}
	mi := &file_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeSetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeSetItem) ProtoMessage() {}

func (x *TradeSetItem) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeSetItem.ProtoReflect.Descriptor instead.
func (*TradeSetItem) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{16}
}

func (x *TradeSetItem) GetInventorySlot() int32 {
	if x != nil {
		return x.InventorySlot
	}
	return 0
}

func (x *TradeSetItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Client -> Server: Set gold in trade
type TradeSetGold struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeSetGold) Reset() {
	*x = TradeSetGold{}
	mi := &file_social_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeSetGold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeSetGold) ProtoMessage() {}

func (x *TradeSetGold) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeSetGold.ProtoReflect.Descriptor instead.
func (*TradeSetGold) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{17}
}

func (x *TradeSetGold) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

// Client -> Server: Confirm trade (ready)
type TradeConfirm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeConfirm) Reset() {
	*x = TradeConfirm{}
	mi := &file_social_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeConfirm) ProtoMessage() {}

func (x *TradeConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeConfirm.ProtoReflect.Descriptor instead.
func (*TradeConfirm) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{18}
}

func (x *TradeConfirm) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

// Server -> Client: Trade window state update
type TradeUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MyItems        []*TradeSlot           `protobuf:"bytes,1,rep,name=my_items,json=myItems,proto3" json:"my_items,omitempty"`
	TheirItems     []*TradeSlot           `protobuf:"bytes,2,rep,name=their_items,json=theirItems,proto3" json:"their_items,omitempty"`
	MyGold         int64                  `protobuf:"varint,3,opt,name=my_gold,json=myGold,proto3" json:"my_gold,omitempty"`
	TheirGold      int64                  `protobuf:"varint,4,opt,name=their_gold,json=theirGold,proto3" json:"their_gold,omitempty"`
	MyConfirmed    bool                   `protobuf:"varint,5,opt,name=my_confirmed,json=myConfirmed,proto3" json:"my_confirmed,omitempty"`
	TheirConfirmed bool                   `protobuf:"varint,6,opt,name=their_confirmed,json=theirConfirmed,proto3" json:"their_confirmed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradeUpdate) Reset() {
	*x = TradeUpdate{}
	mi := &file_social_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeUpdate) ProtoMessage() {}

func (x *TradeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeUpdate.ProtoReflect.Descriptor instead.
func (*TradeUpdate) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{19}
}

func (x *TradeUpdate) GetMyItems() []*TradeSlot {
	if x != nil {
		return x.MyItems
	}
	return nil
}

func (x *TradeUpdate) GetTheirItems() []*TradeSlot {
	if x != nil {
		return x.TheirItems
	}
	return nil
}

func (x *TradeUpdate) GetMyGold() int64 {
	if x != nil {
		return x.MyGold
	}
	return 0
}

func (x *TradeUpdate) GetTheirGold() int64 {
	if x != nil {
		return x.TheirGold
	}
	return 0
}

func (x *TradeUpdate) GetMyConfirmed() bool {
	if x != nil {
		return x.MyConfirmed
	}
	return false
}

func (x *TradeUpdate) GetTheirConfirmed() bool {
	if x != nil {
		return x.TheirConfirmed
	}
	return false
}

type TradeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,4,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeSlot) Reset() {
	*x = TradeSlot{}
	mi := &file_social_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeSlot) ProtoMessage() {}

func (x *TradeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeSlot.ProtoReflect.Descriptor instead.
func (*TradeSlot) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{20}
}

func (x *TradeSlot) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *TradeSlot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TradeSlot) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TradeSlot) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

// Server -> Client: Trade completed or cancelled
type TradeComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeComplete) Reset() {
	*x = TradeComplete{}
	mi := &file_social_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeComplete) ProtoMessage() {}

func (x *TradeComplete) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeComplete.ProtoReflect.Descriptor instead.
func (*TradeComplete) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{21}
}

func (x *TradeComplete) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TradeComplete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Server -> Client: PK status change
type PKStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PkCount       int32                  `protobuf:"varint,1,opt,name=pk_count,json=pkCount,proto3" json:"pk_count,omitempty"`
	EkCount       int32                  `protobuf:"varint,2,opt,name=ek_count,json=ekCount,proto3" json:"ek_count,omitempty"`
	Criminal      bool                   `protobuf:"varint,3,opt,name=criminal,proto3" json:"criminal,omitempty"`                                // true if flagged as criminal
	CriminalTimer int32                  `protobuf:"varint,4,opt,name=criminal_timer,json=criminalTimer,proto3" json:"criminal_timer,omitempty"` // seconds remaining
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PKStatusUpdate) Reset() {
	*x = PKStatusUpdate{}
	mi := &file_social_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PKStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKStatusUpdate) ProtoMessage() {}

func (x *PKStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKStatusUpdate.ProtoReflect.Descriptor instead.
func (*PKStatusUpdate) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{22}
}

func (x *PKStatusUpdate) GetPkCount() int32 {
	if x != nil {
		return x.PkCount
	}
	return 0
}

func (x *PKStatusUpdate) GetEkCount() int32 {
	if x != nil {
		return x.EkCount
	}
	return 0
}

func (x *PKStatusUpdate) GetCriminal() bool {
	if x != nil {
		return x.Criminal
	}
	return false
}

func (x *PKStatusUpdate) GetCriminalTimer() int32 {
	if x != nil {
		return x.CriminalTimer
	}
	return 0
}

var File_social_proto protoreflect.FileDescriptor

const file_social_proto_rawDesc = "" +
	"\n" +
	"\fsocial.proto\x12\bhbonline\"*\n" +
	"\x14FactionSelectRequest\x12\x12\n" +
	"\x04side\x18\x01 \x01(\x05R\x04side\"[\n" +
	"\x15FactionSelectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04side\x18\x03 \x01(\x05R\x04side\"(\n" +
	"\x12GuildCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"M\n" +
	"\x12GuildActionRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x05R\x06action\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\"\xa4\x01\n" +
	"\tGuildInfo\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x05R\aguildId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04side\x18\x03 \x01(\x05R\x04side\x123\n" +
	"\amembers\x18\x04 \x03(\v2\x19.hbonline.GuildMemberInfoR\amembers\x12\x1f\n" +
	"\vmaster_name\x18\x05 \x01(\tR\n" +
	"masterName\"g\n" +
	"\x0fGuildMemberInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\"I\n" +
	"\x13GuildActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x12PartyActionRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x05R\x06action\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\"I\n" +
	"\x13PartyActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"l\n" +
	"\vPartyUpdate\x123\n" +
	"\amembers\x18\x01 \x03(\v2\x19.hbonline.PartyMemberInfoR\amembers\x12(\n" +
	"\x10leader_object_id\x18\x02 \x01(\x05R\x0eleaderObjectId\"\x7f\n" +
	"\x0fPartyMemberInfo\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x05R\bobjectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\"\\\n" +
	"\vPartyInvite\x12*\n" +
	"\x11inviter_object_id\x18\x01 \x01(\x05R\x0finviterObjectId\x12!\n" +
	"\finviter_name\x18\x02 \x01(\tR\vinviterName\"-\n" +
	"\x13PartyInviteResponse\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\"+\n" +
	"\fTradeRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x05R\btargetId\"Y\n" +
	"\rTradeIncoming\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x05R\vrequesterId\x12%\n" +
	"\x0erequester_name\x18\x02 \x01(\tR\rrequesterName\"'\n" +
	"\rTradeResponse\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\"K\n" +
	"\fTradeSetItem\x12%\n" +
	"\x0einventory_slot\x18\x01 \x01(\x05R\rinventorySlot\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\"\n" +
	"\fTradeSetGold\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x03R\x04gold\",\n" +
	"\fTradeConfirm\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed\"\xf7\x01\n" +
	"\vTradeUpdate\x12.\n" +
	"\bmy_items\x18\x01 \x03(\v2\x13.hbonline.TradeSlotR\amyItems\x124\n" +
	"\vtheir_items\x18\x02 \x03(\v2\x13.hbonline.TradeSlotR\n" +
	"theirItems\x12\x17\n" +
	"\amy_gold\x18\x03 \x01(\x03R\x06myGold\x12\x1d\n" +
	"\n" +
	"their_gold\x18\x04 \x01(\x03R\ttheirGold\x12!\n" +
	"\fmy_confirmed\x18\x05 \x01(\bR\vmyConfirmed\x12'\n" +
	"\x0ftheir_confirmed\x18\x06 \x01(\bR\x0etheirConfirmed\"m\n" +
	"\tTradeSlot\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x04 \x01(\x05R\tslotIndex\"C\n" +
	"\rTradeComplete\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x89\x01\n" +
	"\x0ePKStatusUpdate\x12\x19\n" +
	"\bpk_count\x18\x01 \x01(\x05R\apkCount\x12\x19\n" +
	"\bek_count\x18\x02 \x01(\x05R\aekCount\x12\x1a\n" +
	"\bcriminal\x18\x03 \x01(\bR\bcriminal\x12%\n" +
	"\x0ecriminal_timer\x18\x04 \x01(\x05R\rcriminalTimerB0Z.github.com/juanrossi/hbonline/server/pkg/protob\x06proto3"

var (
	file_social_proto_rawDescOnce sync.Once
	file_social_proto_rawDescData []byte
)

func file_social_proto_rawDescGZIP() []byte {
	file_social_proto_rawDescOnce.Do(func() {
		file_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)))
	})
	return file_social_proto_rawDescData
}

var file_social_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_social_proto_goTypes = []any{
	(*FactionSelectRequest)(nil),  // 0: hbonline.FactionSelectRequest
	(*FactionSelectResponse)(nil), // 1: hbonline.FactionSelectResponse
	(*GuildCreateRequest)(nil),    // 2: hbonline.GuildCreateRequest
	(*GuildActionRequest)(nil),    // 3: hbonline.GuildActionRequest
	(*GuildInfo)(nil),             // 4: hbonline.GuildInfo
	(*GuildMemberInfo)(nil),       // 5: hbonline.GuildMemberInfo
	(*GuildActionResponse)(nil),   // 6: hbonline.GuildActionResponse
	(*PartyActionRequest)(nil),    // 7: hbonline.PartyActionRequest
	(*PartyActionResponse)(nil),   // 8: hbonline.PartyActionResponse
	(*PartyUpdate)(nil),           // 9: hbonline.PartyUpdate
	(*PartyMemberInfo)(nil),       // 10: hbonline.PartyMemberInfo
	(*PartyInvite)(nil),           // 11: hbonline.PartyInvite
	(*PartyInviteResponse)(nil),   // 12: hbonline.PartyInviteResponse
	(*TradeRequest)(nil),          // 13: hbonline.TradeRequest
	(*TradeIncoming)(nil),         // 14: hbonline.TradeIncoming
	(*TradeResponse)(nil),         // 15: hbonline.TradeResponse
	(*TradeSetItem)(nil),          // 16: hbonline.TradeSetItem
	(*TradeSetGold)(nil),          // 17: hbonline.TradeSetGold
	(*TradeConfirm)(nil),          // 18: hbonline.TradeConfirm
	(*TradeUpdate)(nil),           // 19: hbonline.TradeUpdate
	(*TradeSlot)(nil),             // 20: hbonline.TradeSlot
	(*TradeComplete)(nil),         // 21: hbonline.TradeComplete
	(*PKStatusUpdate)(nil),        // 22: hbonline.PKStatusUpdate
}
var file_social_proto_depIdxs = []int32{
	5,  // 0: hbonline.GuildInfo.members:type_name -> hbonline.GuildMemberInfo
	10, // 1: hbonline.PartyUpdate.members:type_name -> hbonline.PartyMemberInfo
	20, // 2: hbonline.TradeUpdate.my_items:type_name -> hbonline.TradeSlot
	20, // 3: hbonline.TradeUpdate.their_items:type_name -> hbonline.TradeSlot
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_social_proto_init() }
func file_social_proto_init() {
	if File_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_social_proto_goTypes,
		DependencyIndexes: file_social_proto_depIdxs,
		MessageInfos:      file_social_proto_msgTypes,
	}.Build()
	File_social_proto = out.File
	file_social_proto_goTypes = nil
	file_social_proto_depIdxs = nil
}
